type styleVal = {style: string => ReactNative.Style.t}
@module("twrnc") external create: Js.Json.t => styleVal = "create"
@module("./tailwind.config.js") external tailwindConfig: Js.Json.t = "default"
@module("./tailwind.config.js")
external tailWindColors: {
  "borderNeutralBlack": string,
  "borderNeutralHigh": string,
  "borderNeutralMid": string,
  "borderNeutralLow": string,
  "borderNeutralWhite": string,
  "borderPrimaryHigh": string,
  "borderPrimaryMid": string,
  "borderPrimaryLow": string,
  "borderPositiveHigh": string,
  "borderPositiveMid": string,
  "borderPositiveLow": string,
  "borderNegativeHigh": string,
  "borderNegativeMid": string,
  "borderNegativeLow": string,
  "borderInfoHigh": string,
  "borderInfoMid": string,
  "borderInfoLow": string,
  "fillNeutralBlack": string,
  "fillNeutralHigh": string,
  "fillNeutralMid": string,
  "fillNeutralLow": string,
  "fillNeutralWhite": string,
  "fillPrimaryHigh": string,
  "fillPrimaryMid": string,
  "fillPrimaryLow": string,
  "fillPositiveHigh": string,
  "fillPositiveLow": string,
  "fillNegativeHigh": string,
  "fillNegativeLow": string,
  "fillInfoHigh": string,
  "fillInfoLow": string,
  "textBlack": string,
  "textHigh": string,
  "textMid": string,
  "textLow": string,
  "textWhite": string,
  "textPrimary": string,
  "textPrimaryMid": string,
  "textInfo": string,
  "textPositive": string,
  "textNegative": string,
  "textProgress": string,
  "textWarning": string,
  "iconBlack": string,
  "iconWhite": string,
  "iconPrimary": string,
  "iconInfo": string,
  "iconPositive": string,
  "iconNegative": string,
  "iconProgress": string,
  "iconWarning": string,
  "ctaPrimaryActive": string,
  "ctaPrimaryPressed": string,
  "ctaPrimaryDisabled": string,
  "ctaSecondaryActive": string,
  "ctaSecondaryPressed": string,
  "ctaSecondaryDisabled": string,
  "randomColor": string,
  "activeDotColor": string,
  "inActiveDotColor": string,
  "yellowPositive": string,
} = "bridgeColorClass"
let tw = create(tailwindConfig).style
