import { LanguageObj } from '../types';
import { City } from 'config-types';

const defaultAllowedLanguagesWithoutCity: LanguageObj[] = [
    {
        name: 'ENGLISH',
        translatedName: 'English',
    },
    {
        name: 'HINDI',
        translatedName: 'हिन्दी',
    },
    {
        name: 'TAMIL',
        translatedName: 'தமிழ்',
    },
    {
        name: 'TELUGU',
        translatedName: 'తెలుగు',
    },
    {
        name: 'KANNADA',
        translatedName: 'ಕನ್ನಡ',
    },
    {
        name: 'BENGALI',
        translatedName: 'বাংলা',
    },
    {
        name: 'MALAYALAM',
        translatedName: 'മലയാളം',
    },
    {
        name: 'DUTCH',
        translatedName: 'Nederlands',
    },
    {
        name: 'GERMAN',
        translatedName: 'Deutsch',
    },
    {
        name: 'FRENCH',
        translatedName: 'Français',
    },
    {
        name: 'FINNISH',
        translatedName: 'Suomi',
    },
    {
        name: 'SWEDISH',
        translatedName: 'Svenska',
    },
    {
        name: 'GUJARATI',
        translatedName: 'ગુજરાતી',
    },
];

export const defaultAllowedLanguages: Record<City, LanguageObj[]> = {
    default: defaultAllowedLanguagesWithoutCity,
    bangalore: defaultAllowedLanguagesWithoutCity,
    mumbai: defaultAllowedLanguagesWithoutCity,
    delhi: defaultAllowedLanguagesWithoutCity,
    chennai: defaultAllowedLanguagesWithoutCity,
    kolkata: defaultAllowedLanguagesWithoutCity,
    paris: defaultAllowedLanguagesWithoutCity,
    kochi: defaultAllowedLanguagesWithoutCity,
    hyderabad: defaultAllowedLanguagesWithoutCity,
    coimbatore: defaultAllowedLanguagesWithoutCity,
    pondicherry: defaultAllowedLanguagesWithoutCity,
    goa: defaultAllowedLanguagesWithoutCity,
    pune: defaultAllowedLanguagesWithoutCity,
    mysore: defaultAllowedLanguagesWithoutCity,
    tumakuru: defaultAllowedLanguagesWithoutCity,
    noida: defaultAllowedLanguagesWithoutCity,
    gurugram: defaultAllowedLanguagesWithoutCity,
    siliguri: defaultAllowedLanguagesWithoutCity,
    asansol: defaultAllowedLanguagesWithoutCity,
    durgapur: defaultAllowedLanguagesWithoutCity,
    petrapole: defaultAllowedLanguagesWithoutCity,
    trivandrum: defaultAllowedLanguagesWithoutCity,
    thrissur: defaultAllowedLanguagesWithoutCity,
    kozhikode: defaultAllowedLanguagesWithoutCity,
    vellore: defaultAllowedLanguagesWithoutCity,
    hosur: defaultAllowedLanguagesWithoutCity,
    madurai: defaultAllowedLanguagesWithoutCity,
    thanjavur: defaultAllowedLanguagesWithoutCity,
    tirunelveli: defaultAllowedLanguagesWithoutCity,
    salem: defaultAllowedLanguagesWithoutCity,
    trichy: defaultAllowedLanguagesWithoutCity,
    davanagere: defaultAllowedLanguagesWithoutCity,
    shivamogga: defaultAllowedLanguagesWithoutCity,
    hubli: defaultAllowedLanguagesWithoutCity,
    mangalore: defaultAllowedLanguagesWithoutCity,
    gulbarga: defaultAllowedLanguagesWithoutCity,
    udupi: defaultAllowedLanguagesWithoutCity,
    bhubaneswar: defaultAllowedLanguagesWithoutCity,
    cuttack: defaultAllowedLanguagesWithoutCity,
    puri: defaultAllowedLanguagesWithoutCity,
    tamilnaducities: defaultAllowedLanguagesWithoutCity,
    ysCities: defaultAllowedLanguagesWithoutCity,
    alapuzha: defaultAllowedLanguagesWithoutCity,
    idukki: defaultAllowedLanguagesWithoutCity,
    kasarkode: defaultAllowedLanguagesWithoutCity,
    wayanad: defaultAllowedLanguagesWithoutCity,
    kannur: defaultAllowedLanguagesWithoutCity,
    kottayam: defaultAllowedLanguagesWithoutCity,
    palakkad: defaultAllowedLanguagesWithoutCity,
    kolam: defaultAllowedLanguagesWithoutCity,
    minneapolis: defaultAllowedLanguagesWithoutCity,
    chandigarh: defaultAllowedLanguagesWithoutCity,
    jaipur: defaultAllowedLanguagesWithoutCity,
    gangtok: defaultAllowedLanguagesWithoutCity,
    darjeeling: defaultAllowedLanguagesWithoutCity,
    vijayawada: defaultAllowedLanguagesWithoutCity,
    vishakapatnam: defaultAllowedLanguagesWithoutCity,
    guntur: defaultAllowedLanguagesWithoutCity,
    tirupati: defaultAllowedLanguagesWithoutCity,
    kurnool: defaultAllowedLanguagesWithoutCity,
    khammam: defaultAllowedLanguagesWithoutCity,
    karimnagar: defaultAllowedLanguagesWithoutCity,
    nizamabad: defaultAllowedLanguagesWithoutCity,
    mahbubnagar: defaultAllowedLanguagesWithoutCity,
    suryapet: defaultAllowedLanguagesWithoutCity,
    nalgonda: defaultAllowedLanguagesWithoutCity,
    siddipet: defaultAllowedLanguagesWithoutCity,
    rourkela: defaultAllowedLanguagesWithoutCity,
    warangal: defaultAllowedLanguagesWithoutCity,
    pudukkottai: defaultAllowedLanguagesWithoutCity,
    bidar: defaultAllowedLanguagesWithoutCity,
    srinagar: defaultAllowedLanguagesWithoutCity,
    pathanamthitta: defaultAllowedLanguagesWithoutCity,
    shillong: defaultAllowedLanguagesWithoutCity,
    cherrapunji: defaultAllowedLanguagesWithoutCity,
    pulwama: defaultAllowedLanguagesWithoutCity,
    jammu: defaultAllowedLanguagesWithoutCity,
    anantnag: defaultAllowedLanguagesWithoutCity,
    berhampur: defaultAllowedLanguagesWithoutCity,
    sambalpur: defaultAllowedLanguagesWithoutCity,
    bardhaman: defaultAllowedLanguagesWithoutCity,
    ballari: defaultAllowedLanguagesWithoutCity,
    amsterdam: defaultAllowedLanguagesWithoutCity,
    digha: defaultAllowedLanguagesWithoutCity,
    rajkot: defaultAllowedLanguagesWithoutCity,
    somnath: defaultAllowedLanguagesWithoutCity,
    dwarka: defaultAllowedLanguagesWithoutCity,
    ahmedabad: defaultAllowedLanguagesWithoutCity,
    surat: defaultAllowedLanguagesWithoutCity,
    vadodara: defaultAllowedLanguagesWithoutCity,
    jamnagar: defaultAllowedLanguagesWithoutCity,
    birbhum: defaultAllowedLanguagesWithoutCity,
};
