import { City } from 'config-types';
import { pledgeConfig } from '../types';

const defaultPledgeText = {
    showPledge: true,
    pledgeText: {
        en: "Your safety is our priority. We promise that Namma Yatri drivers shall uphold high safety standards. If you feel unsafe due to the driver's actions or behaviour, please report to us. This helps us ensure safer rides for the entire community.",
        hi: 'आपकी सुरक्षा हमारी प्राथमिकता है। हम वादा करते हैं कि Namma Yatri ड्राइवर उच्च सुरक्षा मानकों का पालन करेंगे। यदि आपको ड्राइवर के व्यवहार या कार्यों से असुरक्षा महसूस हो, तो कृपया हमें रिपोर्ट करें। यह पूरे समुदाय के लिए सुरक्षित यात्राएं सुनिश्चित करने में मदद करेगा।',
        kn: 'ನಿಮ್ಮ ಭದ್ರತೆ ನಮ್ಮ ಆದ್ಯತೆಯಾಗಿದೆ. ನಮ್ಮ ಯಶತ್ರಿ ಚಾಲಕರು ಉನ್ನತ ಭದ್ರತಾ ಮಾನದಂಡಗಳನ್ನು ಪಾಲನೆ ಮಾಡುತ್ತಾರೆ ಎಂದು ನಾವು ಭರವಸೆ ನೀಡುತ್ತೇವೆ. ಚಾಲಕರ ಕ್ರಮಗಳು ಅಥವಾ ವರ್ತನೆಯಿಂದ ನಿಮಗೆ ಅಸುರಕ್ಷಿತವಾಗಿದೆ ಎಂಬ ಅನುಭವವಾದರೆ, ದಯವಿಟ್ಟು ನಮಗೆ ವರದಿ ಮಾಡಿ. ಇದು ಸಮುದಾಯದ ಎಲ್ಲರಿಗೂ ಹೆಚ್ಚು ಸುರಕ್ಷಿತ ಪ್ರಯಾಣವನ್ನು ಖಾತ್ರಿಪಡಿಸುತ್ತದೆ.',
        ta: 'உங்கள் பாதுகாப்பே எங்களுடைய முன்னுரிமை. நம்ம யாத்ரி ஓட்டுநர்கள் உயர்ந்த பாதுகாப்பு தரநிலைகளை பின்பற்றுவார்கள் என்று நாங்கள் உறுதி அளிக்கிறோம். ஓட்டுநரின் நடத்தை அல்லது செயல்களில் இருந்து நீங்கள் பாதுகாப்பாக இல்லை என்று உணர்ந்தால், தயவுசெய்து எங்களுக்கு புகார் அளிக்கவும். இது முழு சமூகத்திற்கும் பாதுகாப்பான பயணங்களை உறுதி செய்ய உதவும்.',
        ml: 'നിങ്ങളുടെ സുരക്ഷയാണ് ഞങ്ങളുടെ മുൻഗണന. നമ യാത്രി ഡ്രൈവർമാർ ഉയർന്ന സുരക്ഷാ മാനദണ്ഡങ്ങൾ പാലിക്കും എന്ന് ഞങ്ങൾ വാഗ്ദാനം ചെയ്യുന്നു. ഡ്രൈവറുടെ പെരുമാറ്റം അല്ലെങ്കിൽ പ്രവൃത്തികൾ കാരണം നിങ്ങൾ അസുരക്ഷിതമായി അനുഭവപ്പെടുകയാണെങ്കിൽ, ദയവായി ഞങ്ങളെ അറിയിക്കൂ. ഇത് മുഴുവൻ സമൂഹത്തിനും കൂടുതൽ സുരക്ഷിതമായ യാത്രകൾ ഉറപ്പാക്കുന്നതിന് സഹായകമായിരിക്കും.',
        bn: 'আপনার নিরাপত্তা আমাদের অগ্রাধিকার। আমরা প্রতিশ্রুতি দিচ্ছি যে Namma Yatri চালকরা উচ্চ নিরাপত্তা মান বজায় রাখবেন। যদি চালকের আচরণ বা কর্মকাণ্ডের কারণে আপনি অনিরাপদ অনুভব করেন, তাহলে দয়া করে আমাদের রিপোর্ট করুন। এটি পুরো সম্প্রদায়ের জন্য আরও নিরাপদ যাত্রা নিশ্চিত করতে সাহায্য করবে।',
        te: 'మీ భద్రత మా ప్రాధాన్యత. Namma Yatri డ్రైవర్లు ఉన్నత భద్రతా ప్రమాణాలను పాటిస్తారని మేము హామీ ఇస్తున్నాము. డ్రైవర్ల ప్రవర్తన లేదా చర్యల వల్ల మీరు అసురక్షితంగా భావిస్తే, దయచేసి మాకు నివేదించండి. ఇది మొత్తం సమాజానికి మరింత భద్రత కలిగిన ప్రయాణాలను నిర్ధారించడంలో సహాయపడుతుంది.',
        od: 'ଆପଣଙ୍କର ସୁରକ୍ଷା ଆମ ପ୍ରଥମିକତା। ଆମେ ନିଶ୍ଚିତ କରୁଛୁ ଯେ Namma Yatri ଚାଳକମାନେ ଉଚ୍ଚ ସୁରକ୍ଷା ମାନକକୁ ଅନୁସରିବେ। ଯଦି ଚାଳକଙ୍କର କାର୍ଯ୍ୟ ବା ବ୍ୟବହାର ଦ୍ୱାରା ଆପଣ ଅସୁରକ୍ଷିତ ବୋଧ କରନ୍ତି, ଦୟାକରି ଆମକୁ ଅଭିଯୋଗ କରନ୍ତୁ। ଏହା ସମସ୍ତ ସମୁଦାୟ ପାଇଁ ଅଧିକ ସୁରକ୍ଷିତ ଯାତ୍ରା ନିଶ୍ଚିତ କରିବ।',
        nl: 'Uw veiligheid is onze prioriteit. Wij beloven dat Namma Yatri chauffeurs hoge veiligheidsnormen zullen handhaven. Als u zich onveilig voelt vanwege de acties of het gedrag van de chauffeur, rapporteer dit dan aan ons. Dit helpt ons veiligere ritten voor de hele gemeenschap te garanderen.',
        de: 'Ihre Sicherheit ist unsere Priorität. Wir versprechen, dass Namma Yatri Fahrer hohe Sicherheitsstandards einhalten werden. Wenn Sie sich aufgrund der Handlungen oder des Verhaltens des Fahrers unsicher fühlen, melden Sie dies bitte an uns. Dies hilft uns, sicherere Fahrten für die gesamte Gemeinschaft zu gewährleisten.',
        fr: 'Votre sécurité est notre priorité. Nous promettons que les chauffeurs Namma Yatri respecteront des normes de sécurité élevées. Si vous vous sentez en danger à cause des actions ou du comportement du chauffeur, veuillez nous le signaler. Cela nous aide à assurer des trajets plus sûrs pour toute la communauté.',
        fi: 'Turvallisuutesi on meille ensisijaista. Lupaamme, että Namma Yatri -kuljettajat noudattavat korkeita turvallisuusstandardeja. Jos tunnet olosi turvattomaksi kuljettajan toimien tai käytöksen vuoksi, ilmoita siitä meille. Tämä auttaa meitä varmistamaan turvallisemmat matkat koko yhteisölle.',
        sv: 'Din säkerhet är vår prioritet. Vi lovar att Namma Yatri-förare ska upprätthålla höga säkerhetsstandarder. Om du känner dig osäker på grund av förarens handlingar eller beteende, rapportera det till oss. Detta hjälper oss att säkerställa säkrare resor för hela gemenskapen.',
        gu: 'તમારી સલામતી અમારી પ્રાથમિકતા છે. અમે વચન આપીએ છીએ કે નમ્મા યાત્રી ડ્રાઇવરો ઉચ્ચ સુરક્ષા ધોરણો જાળવશે. જો ડ્રાઇવરની ક્રિયાઓ અથવા વર્તનને કારણે તમને અસુરક્ષિત લાગે, તો કૃપા કરીને અમને જાણ કરો. આ સમગ્ર સમુદાય માટે સુરક્ષિત સવારી સુનિશ્ચિત કરવામાં મદદ કરે છે.',
    },
};

const pledgeForChennai = {
    showPledge: true,
    pledgeText: {
        en: 'We promise that Namma Yatri drivers will never ask extra fare from you. If they ask, please report to us. This will help other customers have smooth ride.',
        hi: 'हम वादा करते हैं कि Namma Yatri ड्राइवर आपसे कभी भी अतिरिक्त किराया नहीं मांगेंगे। यदि वे मांगते हैं, तो कृपया हमें रिपोर्ट करें। इससे अन्य ग्राहकों को सुगम यात्रा में मदद मिलेगी।',
        kn: 'ನಾವು ನಮ್ಮ ಯಶತ್ರಿ ಚಾಲಕರು ನಿಮ್ಮಿಂದ ಹೆಚ್ಚುವರಿ ದರವನ್ನು ಕೇಳುವುದಿಲ್ಲ ಎಂಬ ವಾಗ್ದಾನವನ್ನು ಕೊಡುತ್ತೇವೆ. ಅವರು ಕೇಳಿದರೆ, ದಯವಿಟ್ಟು ನಮಗೆ ವರದಿ ಮಾಡಿ. ಇದು ಇತರ ಗ್ರಾಹಕರಿಗೆ ಸುಗಮವಾದ ಪ್ರಯಾಣವನ್ನು ಒದಗಿಸುತ್ತದೆ.',
        ta: 'நாங்கள் நம்ம யாத்ரி ஓட்டுநர்கள் உங்களிடமிருந்து கூடுதல் கட்டணம் கேட்க மாட்டார்கள் என்று உறுதி அளிக்கிறோம். அவர்கள் கேட்டால், தயவுசெய்து எங்களுக்கு புகார் தெரிவிக்கவும். இது பிற பயணிகளுக்கும் இலகுவான பயணத்தை வழங்க உதவும்.',
        ml: 'നമ്മ യാത്രി ഡ്രൈവേഴ്സ് നിങ്ങളുടെ પાસിൽ നിന്ന് അധിക നിരക്ക് ആവശ്യപ്പെടില്ലെന്ന് ഞങ്ങൾ വാഗ്ദാനം ചെയ്യുന്നു. അവർ ആവശ്യപ്പെടുന്നുവെങ്കിൽ, ദയവായി ഞങ്ങളെ അറിയിക്കൂ. ഇത് മറ്റു ഉപഭോക്താക്കൾക്ക് സുഖപ്രദമായ യാത്രയ്ക്കായി സഹായകരമായിരിക്കും.',
        bn: 'আমরা প্রতিশ্রুতি দিচ্ছি যে নম্মা যাত্রী চালকেরা আপনাদের কাছ থেকে অতিরিক্ত ভাড়া চাইবেন না। যদি তারা চায়, দয়া করে আমাদের রিপোর্ট করুন। এটি অন্যান্য যাত্রীদের জন্য মসৃণ যাত্রায় সাহায্য করবে।',
        te: 'నమ యాత్రి డ్రైవర్లు మిమ్మల్ని అదనపు చార్జీలు అడగరని మేము హామీ ఇస్తున్నాము. వారు అడిగితే, దయచేసి మాకు నివేదించండి. ఇది ఇతర ప్రయాణికులకు సులభమైన ప్రయాణాన్ని అందించడంలో సహాయపడుతుంది.',
        od: 'ଆମେ ପ୍ରତିଶ୍ରୁତି ଦେଉଛୁ ଯେ Namma Yatri ଚାଳକମାନେ କେବେ ବି ଆପଣଙ୍କ ପାଖରୁ ଅତିରିକ୍ତ ଭାଡା ଚାହିବେ ନାହିଁ। ସେମାନେ ଚାହିଲେ, ଦୟାକରି ଆମକୁ ଅଭିଯୋଗ କରନ୍ତୁ। ଏହି କାର୍ଯ୍ୟ ଅନ୍ୟ ଗ୍ରାହକଙ୍କୁ ସୁବିଧାଜନକ ଯାତ୍ରା ଦେବାରେ ସାହାଯ୍ୟ କରିବ।',
        nl: 'Wij beloven dat Namma Yatri chauffeurs nooit extra tarief van u zullen vragen. Als zij dit vragen, rapporteer dit dan aan ons. Dit zal andere klanten helpen een soepele rit te hebben.',
        de: 'Wir versprechen, dass Namma Yatri Fahrer niemals einen zusätzlichen Fahrpreis von Ihnen verlangen werden. Wenn sie dies tun, melden Sie es bitte an uns. Dies wird anderen Kunden helfen, eine reibungslose Fahrt zu haben.',
        fr: "Nous promettons que les chauffeurs Namma Yatri ne vous demanderont jamais de tarif supplémentaire. S'ils le font, veuillez nous le signaler. Cela aidera les autres clients à avoir un trajet fluide.",
        fi: 'Lupaamme, että Namma Yatri -kuljettajat eivät koskaan pyydä sinulta ylimääräistä maksua. Jos he pyytävät, ilmoita siitä meille. Tämä auttaa muita asiakkaita saamaan sujuvan matkan.',
        sv: 'Vi lovar att Namma Yatri-förare aldrig kommer att begära extra avgift från dig. Om de gör det, rapportera det till oss. Detta kommer att hjälpa andra kunder att få en smidig resa.',
        gu: 'અમે વચન આપીએ છીએ કે નમ્મા યાત્રી ડ્રાઇવરો તમારી પાસેથી ક્યારેય વધારાનું ભાડું માગશે નહીં. જો તેઓ માગે, તો કૃપા કરીને અમને જાણ કરો. આ અન્ય ગ્રાહકોને સરળ સવારી કરવામાં મદદ કરશે.',
    },
};

const pledgeForOtherapps = {
    showPledge: true,
    pledgeText: {
        en: "Your safety is our priority. We promise that our drivers shall uphold high safety standards. If you feel unsafe due to the driver's actions or behaviour, please report to us. This helps us ensure safer rides for the entire community.",
        hi: 'आपकी सुरक्षा हमारी प्राथमिकता है। हम वादा करते हैं कि हमारे ड्राइवर उच्च सुरक्षा मानकों का पालन करेंगे। यदि ड्राइवर के कार्यों या व्यवहार के कारण आप असुरक्षित महसूस करते हैं, तो कृपया हमें रिपोर्ट करें। इससे हमें पूरे समुदाय के लिए सुरक्षित सवारी सुनिश्चित करने में मदद मिलती है।',
        kn: 'ನಿಮ್ಮ ಸುರಕ್ಷತೆಯು ನಮ್ಮ ಆದ್ಯತೆ. ನಮ್ಮ ಚಾಲಕರು ಉನ್ನತ ಸುರಕ್ಷತಾ ಮಾನದಂಡಗಳನ್ನು ಎತ್ತಿಹಿಡಿಯುತ್ತಾರೆಂದು ನಾವು ಭರವಸೆ ನೀಡುತ್ತೇವೆ. ಚಾಲಕನ ಕ್ರಮಗಳು ಅಥವಾ ವರ್ತನೆಯಿಂದ ನೀವು ಅಭದ್ರತೆಯನ್ನು ಅನುಭವಿಸಿದರೆ, ದಯವಿಟ್ಟು ನಮಗೆ ವರದಿ ಮಾಡಿ. ಇದು ಇಡೀ ಸಮುದಾಯಕ್ಕೆ ಸುರಕ್ಷಿತ ಸವಾರಿಗಳನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ನಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
        ta: 'உங்கள் பாதுகாப்பு எங்கள் முன்னுரிமை. எங்கள் ஓட்டுநர்கள் உயர் பாதுகாப்பு தரங்களை கடைபிடிப்பார்கள் என்று நாங்கள் உறுதியளிக்கிறோம். ஓட்டுநரின் செயல்கள் அல்லது நடத்தைகள் காரணமாக நீங்கள் பாதுகாப்பற்றதாக உணர்ந்தால், தயவுசெய்து எங்களிடம் புகாரளிக்கவும். இது முழு சமூகத்திற்கும் பாதுகாப்பான பயணங்களை உறுதிப்படுத்த எங்களுக்கு உதவுகிறது.',
        ml: 'നിങ്ങളുടെ സുരക്ഷയാണ് ഞങ്ങളുടെ മുൻഗണന. ഞങ്ങളുടെ ഡ്രൈവർമാർ ഉയർന്ന സുരക്ഷാ മാനദണ്ഡങ്ങൾ ഉയർത്തിപ്പിടിക്കുമെന്ന് ഞങ്ങൾ വാഗ്ദാനം ചെയ്യുന്നു. ഡ്രൈവറുടെ പ്രവർത്തനങ്ങൾ അല്ലെങ്കിൽ പെരുമാറ്റം കാരണം നിങ്ങൾക്ക് സുരക്ഷിതമല്ലാത്തതായി തോന്നുകയാണെങ്കിൽ, ദയവായി ഞങ്ങളെ അറിയിക്കുക. ഇത് മുഴുവൻ സമൂഹത്തിനും സുരക്ഷിതമായ റൈഡുകൾ ഉറപ്പാക്കാൻ ഞങ്ങളെ സഹായിക്കുന്നു.',
        bn: 'আপনার নিরাপত্তা আমাদের অগ্রাধিকার। আমরা প্রতিশ্রুতি দিচ্ছি যে আমাদের চালকরা উচ্চ নিরাপত্তা মান বজায় রাখবেন। চালকের কাজ বা আচরণের কারণে আপনি যদি असुरक्षित বোধ করেন তবে দয়া করে আমাদের কাছে রিপোর্ট করুন। এটি আমাদের পুরো সম্প্রদায়ের জন্য নিরাপদ রাইড নিশ্চিত করতে সাহায্য করে।',
        te: 'మీ భద్రత మా ప్రాధాన్యం. మా డ్రైవర్లు అత్యున్నత భద్రతా ప్రమాణాలను పాటిస్తారని మేము ప్రామిస్ చేస్తున్నాము. డ్రైవర్ చర్యలు లేదా ప్రవర్తన కారణంగా మీరు అసురక్షితంగా భావిస్తే, దయచేసి మాకు నివేదించండి. ఇది మొత్తం సంఘం కోసం సురక్షితమైన రైడ్‌లను నిర్ధారించడంలో మాకు సహాయపడుతుంది.',
        od: 'ଆପଣଙ୍କର ସୁରକ୍ଷା ଆମର ପ୍ରାଥମିକତା ଅଟେ। ଆମେ ପ୍ରତିଜ୍ଞା କରୁଛୁ ଯେ ଆମର ଡ୍ରାଇଭରମାନେ ଉଚ୍ଚ ସୁରକ୍ଷା ମାନଦଣ୍ଡ ବଜାୟ ରଖିବେ। ଡ୍ରାଇଭରଙ୍କ କାର୍ଯ୍ୟ କିମ୍ବା ଆଚରଣ ଯୋଗୁଁ ଯଦି ଆପଣ ଅସୁରକ୍ଷିତ ଅନୁଭବ କରନ୍ତି, ତେବେ ଦୟାକରି ଆମକୁ ଜଣାନ୍ତୁ। ଏହା ସମଗ୍ର ସମ୍ପ୍ରଦାୟ ପାଇଁ ନିରାପଦ ଯାତ୍ରା ନିଶ୍ଚିତ କରିବାରେ ଆମକୁ ସାହାଯ୍ୟ କରିଥାଏ।',
        nl: 'Uw veiligheid is onze prioriteit. Wij beloven dat onze chauffeurs hoge veiligheidsnormen zullen handhaven. Als u zich onveilig voelt vanwege de acties of het gedrag van de chauffeur, rapporteer dit dan aan ons. Dit helpt ons veiligere ritten voor de hele gemeenschap te garanderen.',
        de: 'Ihre Sicherheit ist unsere Priorität. Wir versprechen, dass unsere Fahrer hohe Sicherheitsstandards einhalten werden. Wenn Sie sich aufgrund der Handlungen oder des Verhaltens des Fahrers unsicher fühlen, melden Sie dies bitte an uns. Dies hilft uns, sicherere Fahrten für die gesamte Gemeinschaft zu gewährleisten.',
        fr: 'Votre sécurité est notre priorité. Nous promettons que nos chauffeurs respecteront des normes de sécurité élevées. Si vous vous sentez en danger à cause des actions ou du comportement du chauffeur, veuillez nous le signaler. Cela nous aide à assurer des trajets plus sûrs pour toute la communauté.',
        fi: 'Turvallisuutesi on meille ensisijaista. Lupaamme, että kuljettajamme noudattavat korkeita turvallisuusstandardeja. Jos tunnet olosi turvattomaksi kuljettajan toimien tai käytöksen vuoksi, ilmoita siitä meille. Tämä auttaa meitä varmistamaan turvallisemmat matkat koko yhteisölle.',
        sv: 'Din säkerhet är vår prioritet. Vi lovar att våra förare ska upprätthålla höga säkerhetsstandarder. Om du känner dig osäker på grund av förarens handlingar eller beteende, rapportera det till oss. Detta hjälper oss att säkerställa säkrare resor för hela gemenskapen.',
        gu: 'તમારી સલામતી અમારી પ્રાથમિકતા છે. અમે વચન આપીએ છીએ કે અમારા ડ્રાઇવરો ઉચ્ચ સુરક્ષા ધોરણો જાળવશે. જો ડ્રાઇવરની ક્રિયાઓ અથવા વર્તનને કારણે તમને અસુરક્ષિત લાગે, તો કૃપા કરીને અમને જાણ કરો. આ સમગ્ર સમુદાય માટે સુરક્ષિત સવારી સુનિશ્ચિત કરવામાં અમને મદદ કરે છે.',
    },
};

const disabledPledgeConfig = {
    showPledge: false,
    pledgeText: {
        en: '',
        hi: '',
        kn: '',
        ta: '',
        ml: '',
        bn: '',
        te: '',
        od: '',
        nl: '',
        de: '',
        fr: '',
        fi: '',
        sv: '',
        gu: '',
    },
};

export const defaultPledgeConfig: Record<City, pledgeConfig> = {
    bangalore: defaultPledgeText,
    mumbai: defaultPledgeText,
    delhi: disabledPledgeConfig,
    chennai: pledgeForChennai,
    kolkata: pledgeForOtherapps,
    paris: defaultPledgeText,
    kochi: pledgeForOtherapps,
    hyderabad: defaultPledgeText,
    coimbatore: defaultPledgeText,
    pondicherry: defaultPledgeText,
    goa: defaultPledgeText,
    pune: defaultPledgeText,
    mysore: defaultPledgeText,
    tumakuru: defaultPledgeText,
    noida: disabledPledgeConfig,
    gurugram: disabledPledgeConfig,
    siliguri: pledgeForOtherapps,
    asansol: pledgeForOtherapps,
    durgapur: pledgeForOtherapps,
    petrapole: defaultPledgeText,
    trivandrum: pledgeForOtherapps,
    thrissur: pledgeForOtherapps,
    kozhikode: pledgeForOtherapps,
    vellore: defaultPledgeText,
    hosur: defaultPledgeText,
    madurai: defaultPledgeText,
    thanjavur: defaultPledgeText,
    tirunelveli: defaultPledgeText,
    salem: defaultPledgeText,
    trichy: defaultPledgeText,
    davanagere: defaultPledgeText,
    shivamogga: defaultPledgeText,
    hubli: defaultPledgeText,
    mangalore: defaultPledgeText,
    gulbarga: defaultPledgeText,
    udupi: defaultPledgeText,
    bhubaneswar: pledgeForOtherapps,
    tamilnaducities: pledgeForChennai,
    ysCities: pledgeForOtherapps,
    cuttack: pledgeForOtherapps,
    puri: pledgeForOtherapps,
    alapuzha: pledgeForOtherapps,
    idukki: pledgeForOtherapps,
    kasarkode: pledgeForOtherapps,
    wayanad: pledgeForOtherapps,
    kannur: pledgeForOtherapps,
    kottayam: pledgeForOtherapps,
    palakkad: pledgeForOtherapps,
    kolam: pledgeForOtherapps,
    default: defaultPledgeText,
    minneapolis: defaultPledgeText,
    chandigarh: defaultPledgeText,
    jaipur: defaultPledgeText,
    gangtok: defaultPledgeText,
    darjeeling: defaultPledgeText,
    vijayawada: defaultPledgeText,
    vishakapatnam: defaultPledgeText,
    guntur: defaultPledgeText,
    tirupati: defaultPledgeText,
    kurnool: defaultPledgeText,
    khammam: defaultPledgeText,
    karimnagar: defaultPledgeText,
    nizamabad: defaultPledgeText,
    mahbubnagar: defaultPledgeText,
    suryapet: defaultPledgeText,
    nalgonda: defaultPledgeText,
    siddipet: defaultPledgeText,
    rourkela: defaultPledgeText,
    warangal: defaultPledgeText,
    pudukkottai: defaultPledgeText,
    bidar: defaultPledgeText,
    srinagar: defaultPledgeText,
    pathanamthitta: defaultPledgeText,
    shillong: defaultPledgeText,
    cherrapunji: defaultPledgeText,
    pulwama: defaultPledgeText,
    jammu: defaultPledgeText,
    anantnag: defaultPledgeText,
    berhampur: defaultPledgeText,
    sambalpur: defaultPledgeText,
    bardhaman: defaultPledgeText,
    ballari: defaultPledgeText,
    amsterdam: defaultPledgeText,
    digha: defaultPledgeText,
    rajkot: disabledPledgeConfig,
    somnath: disabledPledgeConfig,
    dwarka: disabledPledgeConfig,
    ahmedabad: disabledPledgeConfig,
    surat: disabledPledgeConfig,
    vadodara: disabledPledgeConfig,
    jamnagar: disabledPledgeConfig,
    birbhum: disabledPledgeConfig,
};

export default defaultPledgeConfig;
