import { City } from 'config-types';
import { BusinessProfileConfig } from '../types';
import { ServiceTierType_serviceTierType } from '@/readOnly/api/types/Enums.gen';

const defaultBusinessEstimatedOrder: ServiceTierType_serviceTierType[] = [
    'COMFY',
    'ECO',
    'TAXI',
    'AUTO_PLUS',
    'AUTO_RICKSHAW',
    'SUV',
    'SUV_PLUS',
];

const defaultConfig: BusinessProfileConfig = {
    pollingTime: 5000,
    maxPollTimeout: 30 * 60 * 1000, // 30 minutes in milliseconds
    showNewTag: true,
    enableBusinessProfile: false,
    businessEstimatedOrder: defaultBusinessEstimatedOrder,
};

export const defaultBusinessProfileConfig: Record<City, BusinessProfileConfig> = {
    bangalore: {
        pollingTime: 5000,
        maxPollTimeout: 30 * 60 * 1000, // 30 minutes in milliseconds
        showNewTag: true,
        enableBusinessProfile: true,
        businessEstimatedOrder: defaultBusinessEstimatedOrder,
    },
    mumbai: defaultConfig,
    delhi: defaultConfig,
    chennai: defaultConfig,
    kolkata: defaultConfig,
    paris: defaultConfig,
    kochi: defaultConfig,
    hyderabad: defaultConfig,
    coimbatore: defaultConfig,
    pondicherry: defaultConfig,
    goa: defaultConfig,
    pune: defaultConfig,
    mysore: defaultConfig,
    tumakuru: defaultConfig,
    noida: defaultConfig,
    gurugram: defaultConfig,
    siliguri: defaultConfig,
    asansol: defaultConfig,
    durgapur: defaultConfig,
    petrapole: defaultConfig,
    trivandrum: defaultConfig,
    thrissur: defaultConfig,
    kozhikode: defaultConfig,
    vellore: defaultConfig,
    hosur: defaultConfig,
    madurai: defaultConfig,
    thanjavur: defaultConfig,
    tirunelveli: defaultConfig,
    salem: defaultConfig,
    trichy: defaultConfig,
    davanagere: defaultConfig,
    shivamogga: defaultConfig,
    hubli: defaultConfig,
    mangalore: defaultConfig,
    gulbarga: defaultConfig,
    udupi: defaultConfig,
    bhubaneswar: defaultConfig,
    tamilnaducities: defaultConfig,
    ysCities: defaultConfig,
    cuttack: defaultConfig,
    puri: defaultConfig,
    alapuzha: defaultConfig,
    idukki: defaultConfig,
    kasarkode: defaultConfig,
    wayanad: defaultConfig,
    kannur: defaultConfig,
    kottayam: defaultConfig,
    palakkad: defaultConfig,
    kolam: defaultConfig,
    minneapolis: defaultConfig,
    chandigarh: defaultConfig,
    jaipur: defaultConfig,
    gangtok: defaultConfig,
    darjeeling: defaultConfig,
    vijayawada: defaultConfig,
    vishakapatnam: defaultConfig,
    guntur: defaultConfig,
    tirupati: defaultConfig,
    kurnool: defaultConfig,
    khammam: defaultConfig,
    karimnagar: defaultConfig,
    nizamabad: defaultConfig,
    mahbubnagar: defaultConfig,
    suryapet: defaultConfig,
    nalgonda: defaultConfig,
    siddipet: defaultConfig,
    rourkela: defaultConfig,
    warangal: defaultConfig,
    pudukkottai: defaultConfig,
    bidar: defaultConfig,
    srinagar: defaultConfig,
    pathanamthitta: defaultConfig,
    shillong: defaultConfig,
    cherrapunji: defaultConfig,
    pulwama: defaultConfig,
    jammu: defaultConfig,
    anantnag: defaultConfig,
    berhampur: defaultConfig,
    bardhaman: defaultConfig,
    ballari: defaultConfig,
    amsterdam: defaultConfig,
    digha: defaultConfig,
    rajkot: defaultConfig,
    somnath: defaultConfig,
    dwarka: defaultConfig,
    ahmedabad: defaultConfig,
    surat: defaultConfig,
    vadodara: defaultConfig,
    jamnagar: defaultConfig,
    default: defaultConfig,
    birbhum: defaultConfig,
    sambalpur: defaultConfig,
};
