import { City } from 'config-types/dist/domain/factors/city';
import { LottieConfigs } from '../types';

const defaultLottieConfig: LottieConfigs = {
    homeScreenLottieUrl: {
        lottieUrl:
            'https://raw.githubusercontent.com/witcher-shailesh/github-asset-store/main/uploads/greetingLottie/file-mt_ic_hi_lottie2-1753372565348.lottie',
        androidBottomOffset: 450,
        iosBottomOffset: 450,
        customWidth: 940,
        customHeight: 940,
        zoomPercent: 100,
    },
};

export const defaultLottieConfigs: Record<City, LottieConfigs> = {
    default: defaultLottieConfig,
    bangalore: defaultLottieConfig,
    mumbai: defaultLottieConfig,
    delhi: defaultLottieConfig,
    chennai: defaultLottieConfig,
    kolkata: defaultLottieConfig,
    paris: defaultLottieConfig,
    kochi: defaultLottieConfig,
    hyderabad: defaultLottieConfig,
    coimbatore: defaultLottieConfig,
    pondicherry: defaultLottieConfig,
    goa: defaultLottieConfig,
    pune: defaultLottieConfig,
    mysore: defaultLottieConfig,
    tumakuru: defaultLottieConfig,
    noida: defaultLottieConfig,
    gurugram: defaultLottieConfig,
    siliguri: defaultLottieConfig,
    asansol: defaultLottieConfig,
    durgapur: defaultLottieConfig,
    petrapole: defaultLottieConfig,
    trivandrum: defaultLottieConfig,
    thrissur: defaultLottieConfig,
    kozhikode: defaultLottieConfig,
    vellore: defaultLottieConfig,
    hosur: defaultLottieConfig,
    madurai: defaultLottieConfig,
    thanjavur: defaultLottieConfig,
    tirunelveli: defaultLottieConfig,
    salem: defaultLottieConfig,
    trichy: defaultLottieConfig,
    davanagere: defaultLottieConfig,
    shivamogga: defaultLottieConfig,
    hubli: defaultLottieConfig,
    mangalore: defaultLottieConfig,
    gulbarga: defaultLottieConfig,
    udupi: defaultLottieConfig,
    bhubaneswar: defaultLottieConfig,
    cuttack: defaultLottieConfig,
    puri: defaultLottieConfig,
    tamilnaducities: defaultLottieConfig,
    ysCities: defaultLottieConfig,
    alapuzha: defaultLottieConfig,
    idukki: defaultLottieConfig,
    kasarkode: defaultLottieConfig,
    wayanad: defaultLottieConfig,
    kannur: defaultLottieConfig,
    kottayam: defaultLottieConfig,
    palakkad: defaultLottieConfig,
    kolam: defaultLottieConfig,
    minneapolis: defaultLottieConfig,
    chandigarh: defaultLottieConfig,
    jaipur: defaultLottieConfig,
    gangtok: defaultLottieConfig,
    darjeeling: defaultLottieConfig,
    vijayawada: defaultLottieConfig,
    vishakapatnam: defaultLottieConfig,
    guntur: defaultLottieConfig,
    tirupati: defaultLottieConfig,
    kurnool: defaultLottieConfig,
    khammam: defaultLottieConfig,
    karimnagar: defaultLottieConfig,
    nizamabad: defaultLottieConfig,
    mahbubnagar: defaultLottieConfig,
    suryapet: defaultLottieConfig,
    nalgonda: defaultLottieConfig,
    siddipet: defaultLottieConfig,
    rourkela: defaultLottieConfig,
    warangal: defaultLottieConfig,
    pudukkottai: defaultLottieConfig,
    bidar: defaultLottieConfig,
    srinagar: defaultLottieConfig,
    pathanamthitta: defaultLottieConfig,
    shillong: defaultLottieConfig,
    cherrapunji: defaultLottieConfig,
    pulwama: defaultLottieConfig,
    jammu: defaultLottieConfig,
    anantnag: defaultLottieConfig,
    berhampur: defaultLottieConfig,
    sambalpur: defaultLottieConfig,
    bardhaman: defaultLottieConfig,
    ballari: defaultLottieConfig,
    amsterdam: defaultLottieConfig,
    digha: defaultLottieConfig,
    rajkot: defaultLottieConfig,
    somnath: defaultLottieConfig,
    dwarka: defaultLottieConfig,
    ahmedabad: defaultLottieConfig,
    surat: defaultLottieConfig,
    vadodara: defaultLottieConfig,
    jamnagar: defaultLottieConfig,
    birbhum: defaultLottieConfig,
};
