import { rotatingTexts } from '../types';

const defaultConfig: rotatingTexts[] = [
    {
        duration: 6,
        texts: {
            en: 'Broadcasting a boosted search!',
            kn: 'ಹೆಚ್ಚಿಸಿದ ಹುಡುಕಾಟವನ್ನು ಪ್ರಸಾರ ಮಾಡಲಾಗುತ್ತಿದೆ!',
            hi: 'बूस्टेड सर्च का प्रसारण किया जा रहा है!',
            ta: 'பூஸ்ட் செய்யப்பட்ட தேடலை ஒளிபரப்புகிறது!',
            te: 'బూస్ట్ చేసిన శోధనను ప్రసారం చేస్తున్నాం!',
            bn: 'বুস্টেড সার্চ প্রচার করা হচ্ছে!',
            ml: 'ബൂസ്റ്റഡ് തിരയൽ പ്രക്ഷേപണം ചെയ്യുന്നു!',
            od: 'ବୁଷ୍ଟେଡ୍ ସର୍ଚ୍ଚ ପ୍ରସାରଣ କରାଯାଉଛି!',
            nl: 'Versterkte zoekopdracht uitzenden!',
            de: 'Verstärkte Suche wird übertragen!',
            fr: "Diffusion d'une recherche boostée !",
            fi: 'Lähetetään tehostettua hakua!',
            sv: 'Skickar förstärkt sökning!',
            gu: 'બૂસ્ટેડ સર્ચ પ્રસારિત કરી રહ્યા છીએ!',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Request sent to drivers',
            kn: 'ಚಾಲಕರಿಗೆ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ',
            hi: 'ड्राइवरों को अनुरोध भेजा गया',
            ta: 'டிரைவர்களுக்கு கோரிக்கை அனுப்பப்பட்டது',
            te: 'డ్రైవర్లకు అభ్యర్థన పంపాం',
            bn: 'ড্রাইভারদের অনুরোধ পাঠানো হয়েছে',
            ml: 'ഡ്രൈവർമാർക്ക് അഭ്യർത്ഥന അയച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ କୁ ଅନୁରୋଧ ପଠାଯାଇଛି',
            nl: 'Verzoek verzonden naar chauffeurs',
            de: 'Anfrage an Fahrer gesendet',
            fr: 'Demande envoyée aux chauffeurs',
            fi: 'Pyyntö lähetetty kuljettajille',
            sv: 'Förfrågan skickad till förare',
            gu: 'ડ્રાઇવરોને વિનંતી મોકલી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Awaiting driver response',
            kn: 'ಚಾಲಕರ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಕಾಯುತ್ತಿದ್ದೇವೆ',
            hi: 'ड्राइवर की प्रतिक्रिया का इंतज़ार',
            ta: 'டிரைவரின் பதிலை காத்திருக்கிறோம்',
            te: 'డ్రైవర్ల స్పందన కోసం చూస్తున్నాం',
            bn: 'ড্রাইভারের উত্তর আসার অপেক্ষা',
            ml: 'ഡ്രൈവറിന്റെ പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു',
            od: 'ଡ୍ରାଇଭରଙ୍କ ପ୍ରତିକ୍ରିୟା ଅପେକ୍ଷା କରୁଛୁ',
            nl: 'Wachten op reactie van chauffeur',
            de: 'Warten auf Fahrerantwort',
            fr: 'En attente de la réponse du chauffeur',
            fi: 'Odotetaan kuljettajan vastausta',
            sv: 'Väntar på förarens svar',
            gu: 'ડ્રાઇવરના જવાબની રાહ જોઈ રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Expanding search area',
            kn: 'ಹುಡುಕಾಟ ಪ್ರದೇಶ ವಿಸ್ತರಿಸಲಾಗುತ್ತಿದೆ',
            hi: 'खोज क्षेत्र बढ़ाया जा रहा है',
            ta: 'தேடல் பரப்பை விரிவாக்குகிறோம்',
            te: 'శోధన పరిధిని పెంచుతున్నాం',
            bn: 'অনুসন্ধানের পরিসর বাড়ানো হচ্ছে',
            ml: 'തിരച്ചിലിന്റെ പരിധി വികസിപ്പിക്കുന്നു',
            od: 'ସନ୍ଧାନ କ୍ଷେତ୍ର ବଢ଼ାଯାଉଛି',
            nl: 'Zoekgebied uitbreiden',
            de: 'Suchbereich erweitern',
            fr: 'Élargissement de la zone de recherche',
            fi: 'Laajennetaan hakualuetta',
            sv: 'Utökar sökområdet',
            gu: 'શોધ વિસ્તાર વધારી રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Checking for available drivers',
            kn: 'ಲಭ್ಯವಿರುವ ಚಾಲಕರಿಗಾಗಿ ಪರಿಶೀಲಿಸುತ್ತಿದ್ದೇವೆ',
            hi: 'उपलब्ध ड्राइवरों की जांच कर रहे हैं',
            ta: 'கிடைக்கும் டிரைவர்களை பார்க்கிறோம்',
            te: 'లభ్యమైన డ్రైవర్లను చూస్తున్నాం',
            bn: 'উপলব্ধ ড্রাইভারদের দেখছি',
            ml: 'ലഭ്യമായ ഡ്രൈവർമാരെ പരിശോധിക്കുന്നു',
            od: 'ଉପଲବ୍ଧ ଡ୍ରାଇଭରମାନେ କୁ ଦେଖୁଛୁ',
            nl: 'Controleren op beschikbare chauffeurs',
            de: 'Verfügbare Fahrer prüfen',
            fr: 'Vérification des chauffeurs disponibles',
            fi: 'Tarkistetaan saatavilla olevia kuljettajia',
            sv: 'Kontrollerar tillgängliga förare',
            gu: 'ઉપલબ્ધ ડ્રાઇવરો શોધી રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Found more drivers nearby',
            kn: 'ಹತ್ತಿರದಲ್ಲಿರುವ ಹೆಚ್ಚಿನ ಚಾಲಕರನ್ನು ಕಂಡಿದ್ದೇವೆ',
            hi: 'और नज़दीकी ड्राइवर मिले हैं',
            ta: 'அருகில் மேலும் டிரைவர்கள் கிடைத்தனர்',
            te: 'ఇంకా సమీపంలో డ్రైవర్లను కనుగొన్నాం',
            bn: 'আরও কাছাকাছি ড্রাইভার খুঁজে পেয়েছি',
            ml: 'കൂടുതൽ സമീപ ഡ്രൈവർമാരെ കണ്ടെത്തി',
            od: 'ଅଧିକ ନିକଟ ଡ୍ରାଇଭର ମିଳିଛନ୍ତି',
            nl: 'Meer chauffeurs in de buurt gevonden',
            de: 'Mehr Fahrer in der Nähe gefunden',
            fr: 'Plus de chauffeurs trouvés à proximité',
            fi: 'Löytyi lisää kuljettajia lähistöltä',
            sv: 'Hittade fler förare i närheten',
            gu: 'નજીકમાં વધુ ડ્રાઇવરો મળ્યા',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Request sent to drivers',
            kn: 'ಚಾಲಕರಿಗೆ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ',
            hi: 'ड्राइवरों को अनुरोध भेजा गया',
            ta: 'டிரைவர்களுக்கு கோரிக்கை அனுப்பப்பட்டது',
            te: 'డ్రైవర్లకు అభ్యర్థన పంపాం',
            bn: 'ড্রাইভারদের অনুরোধ পাঠানো হয়েছে',
            ml: 'ഡ്രൈവർമാർക്ക് അഭ്യർത്ഥന അയച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ କୁ ଅନୁରୋଧ ପଠାଯାଇଛି',
            nl: 'Verzoek verzonden naar chauffeurs',
            de: 'Anfrage an Fahrer gesendet',
            fr: 'Demande envoyée aux chauffeurs',
            fi: 'Pyyntö lähetetty kuljettajille',
            sv: 'Förfrågan skickad till förare',
            gu: 'ડ્રાઇવરોને વિનંતી મોકલી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Drivers received your request',
            kn: 'ಚಾಲಕರಿಗೆ ನಿಮ್ಮ ವಿನಂತಿ ಸಿಕ್ಕಿದೆ',
            hi: 'ड्राइवरों को आपका अनुरोध मिला',
            ta: 'டிரைவர்களுக்கு உங்கள் கோரிக்கை வந்தது',
            te: 'డ్రైవర్లకు మీ అభ్యర్థన చేరింది',
            bn: 'ড্রাইভাররা আপনার অনুরোধ পেয়েছে',
            ml: 'ഡ്രൈവർമാർ നിങ്ങളുടെ അഭ്യർത്ഥന സ്വീകരിച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ ଆପଣଙ୍କ ଅନୁରୋଧ ଦେଖିଛନ୍ତି',
            nl: 'Chauffeurs hebben uw verzoek ontvangen',
            de: 'Fahrer haben Ihre Anfrage erhalten',
            fr: 'Les chauffeurs ont reçu votre demande',
            fi: 'Kuljettajat saivat pyyntösi',
            sv: 'Förare fick din förfrågan',
            gu: 'ડ્રાઇવરોને તમારી વિનંતી મળી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Awaiting driver response',
            kn: 'ಚಾಲಕರ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಕಾಯುತ್ತಿದ್ದೇವೆ',
            hi: 'ड्राइवर की प्रतिक्रिया का इंतज़ार',
            ta: 'டிரைவரின் பதிலை காத்திருக்கிறோம்',
            te: 'డ్రైవర్ల స్పందన కోసం చూస్తున్నాం',
            bn: 'ড্রাইভারের উত্তর আসার অপেক্ষা',
            ml: 'ഡ്രൈവറിന്റെ പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു',
            od: 'ଡ୍ରାଇଭରଙ୍କ ପ୍ରତିକ୍ରିୟା ଅପେକ୍ଷା କରୁଛୁ',
            nl: 'Wachten op reactie van chauffeur',
            de: 'Warten auf Fahrerantwort',
            fr: 'En attente de la réponse du chauffeur',
            fi: 'Odotetaan kuljettajan vastausta',
            sv: 'Väntar på förarens svar',
            gu: 'ડ્રાઇવરના જવાબની રાહ જોઈ રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Wait a moment, found more drivers',
            kn: 'ಏನು ಸಮಯ ಕೊಡಿರಿ, ಇನ್ನಷ್ಟು ಚಾಲಕರನ್ನು ಕಂಡಿದ್ದೇವೆ',
            hi: 'थोड़ा इंतज़ार करें, और ड्राइवर मिले हैं',
            ta: 'ஒரு நிமிடம் பொறு, மேலும் டிரைவர்கள் கிடைத்தனர்',
            te: 'ఇంకాసేపు వేచేయండి, డ్రైవర్లు దొరికారు',
            bn: 'একটু অপেক্ষা করুন, আরও ড্রাইভার পেয়েছি',
            ml: 'കുറച്ച് കാത്തിരിക്കുക, കൂടുതൽ ഡ്രൈവർമാരെ കണ്ടെത്തി',
            od: 'ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ, ଅଧିକ ଡ୍ରାଇଭର ମିଳିଛନ୍ତି',
            nl: 'Even wachten, meer chauffeurs gevonden',
            de: 'Warten Sie, mehr Fahrer gefunden',
            fr: 'Un moment, plus de chauffeurs trouvés',
            fi: 'Hetkinen, löytyi lisää kuljettajia',
            sv: 'Vänta lite, hittade fler förare',
            gu: 'થોડી રાહ જુઓ, વધુ ડ્રાઇવરો મળ્યા',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Request sent to drivers',
            kn: 'ಚಾಲಕರಿಗೆ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ',
            hi: 'ड्राइवरों को अनुरोध भेजा गया',
            ta: 'டிரைவர்களுக்கு கோரிக்கை அனுப்பப்பட்டது',
            te: 'డ్రైవర్లకు అభ్యర్థన పంపాం',
            bn: 'ড্রাইভারদের অনুরোধ পাঠানো হয়েছে',
            ml: 'ഡ്രൈവർമാർക്ക് അഭ്യർത്ഥന അയച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ କୁ ଅନୁରୋଧ ପଠାଯାଇଛି',
            nl: 'Verzoek verzonden naar chauffeurs',
            de: 'Anfrage an Fahrer gesendet',
            fr: 'Demande envoyée aux chauffeurs',
            fi: 'Pyyntö lähetetty kuljettajille',
            sv: 'Förfrågan skickad till förare',
            gu: 'ડ્રાઇવરોને વિનંતી મોકલી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Drivers received your request',
            kn: 'ಚಾಲಕರಿಗೆ ನಿಮ್ಮ ವಿನಂತಿ ಸಿಕ್ಕಿದೆ',
            hi: 'ड्राइवरों को आपका अनुरोध मिला',
            ta: 'டிரைவர்களுக்கு உங்கள் கோரிக்கை வந்தது',
            te: 'డ్రైవర్లకు మీ అభ్యర్థన చేరింది',
            bn: 'ড্রাইভাররা আপনার অনুরোধ পেয়েছে',
            ml: 'ഡ്രൈവർമാർ നിങ്ങളുടെ അഭ്യർത്ഥന സ്വീകരിച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ ଆପଣଙ୍କ ଅନୁରୋଧ ଦେଖିଛନ୍ତି',
            nl: 'Chauffeurs hebben uw verzoek ontvangen',
            de: 'Fahrer haben Ihre Anfrage erhalten',
            fr: 'Les chauffeurs ont reçu votre demande',
            fi: 'Kuljettajat saivat pyyntösi',
            sv: 'Förare fick din förfrågan',
            gu: 'ડ્રાઇવરોને તમારી વિનંતી મળી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Awaiting driver response',
            kn: 'ಚಾಲಕರ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಕಾಯುತ್ತಿದ್ದೇವೆ',
            hi: 'ड्राइवर की प्रतिक्रिया का इंतज़ार',
            ta: 'டிரைவரின் பதிலை காத்திருக்கிறோம்',
            te: 'డ్రైవర్ల స్పందన కోసం చూస్తున్నాం',
            bn: 'ড্রাইভারের উত্তর আসার অপেক্ষা',
            ml: 'ഡ്രൈവറിന്റെ പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു',
            od: 'ଡ୍ରାଇଭରଙ୍କ ପ୍ରତିକ୍ରିୟା ଅପେକ୍ଷା କରୁଛୁ',
            nl: 'Wachten op reactie van chauffeur',
            de: 'Warten auf Fahrerantwort',
            fr: 'En attente de la réponse du chauffeur',
            fi: 'Odotetaan kuljettajan vastausta',
            sv: 'Väntar på förarens svar',
            gu: 'ડ્રાઇવરના જવાબની રાહ જોઈ રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Optimizing your ride request',
            kn: 'ನಿಮ್ಮ ರೈಡ್ ವಿನಂತಿಯನ್ನು ಸುಧಾರಿಸುತ್ತಿದ್ದೇವೆ',
            hi: 'आपकी राइड अनुरोध को बेहतर बना रहे हैं',
            ta: 'உங்கள் பயண கோரிக்கையை மேம்படுத்துகிறோம்',
            te: 'మీ రైడ్ అభ్యర్థనను మెరుగుపరుస్తున్నాం',
            bn: 'আপনার রাইড অনুরোধ উন্নত করছি',
            ml: 'റൈഡ് അഭ്യർത്ഥന മെച്ചപ്പെടുത്തുന്നു',
            od: 'ଆପଣଙ୍କ ଅନୁରୋଧ କୁ ଉନ୍ନତ କରୁଛୁ',
            nl: 'Uw ritverzoek optimaliseren',
            de: 'Ihre Fahrtanfrage wird optimiert',
            fr: 'Optimisation de votre demande de course',
            fi: 'Optimoidaan kyytiä pyyntöäsi',
            sv: 'Optimerar din reseförfrågan',
            gu: 'તમારી સવારીની વિનંતી સુધારી રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Request sent to drivers',
            kn: 'ಚಾಲಕರಿಗೆ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ',
            hi: 'ड्राइवरों को अनुरोध भेजा गया',
            ta: 'டிரைவர்களுக்கு கோரிக்கை அனுப்பப்பட்டது',
            te: 'డ్రైవర్లకు అభ్యర్థన పంపాం',
            bn: 'ড্রাইভারদের অনুরোধ পাঠানো হয়েছে',
            ml: 'ഡ്രൈവർമാർക്ക് അഭ്യർത്ഥന അയച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ କୁ ଅନୁରୋଧ ପଠାଯାଇଛି',
            nl: 'Verzoek verzonden naar chauffeurs',
            de: 'Anfrage an Fahrer gesendet',
            fr: 'Demande envoyée aux chauffeurs',
            fi: 'Pyyntö lähetetty kuljettajille',
            sv: 'Förfrågan skickad till förare',
            gu: 'ડ્રાઇવરોને વિનંતી મોકલી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Drivers received your request',
            kn: 'ಚಾಲಕರಿಗೆ ನಿಮ್ಮ ವಿನಂತಿ ಸಿಕ್ಕಿದೆ',
            hi: 'ड्राइवरों को आपका अनुरोध मिला',
            ta: 'டிரைவர்களுக்கு உங்கள் கோரிக்கை வந்தது',
            te: 'డ్రైవర్లకు మీ అభ్యర్థన చేరింది',
            bn: 'ড্রাইভাররা আপনার অনুরোধ পেয়েছে',
            ml: 'ഡ്രൈവർമാർ നിങ്ങളുടെ അഭ്യർത്ഥന സ്വീകരിച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ ଆପଣଙ୍କ ଅନୁରୋଧ ଦେଖିଛନ୍ତି',
            nl: 'Chauffeurs hebben uw verzoek ontvangen',
            de: 'Fahrer haben Ihre Anfrage erhalten',
            fr: 'Les chauffeurs ont reçu votre demande',
            fi: 'Kuljettajat saivat pyyntösi',
            sv: 'Förare fick din förfrågan',
            gu: 'ડ્રાઇવરોને તમારી વિનંતી મળી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Awaiting driver response',
            kn: 'ಚಾಲಕರ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಕಾಯುತ್ತಿದ್ದೇವೆ',
            hi: 'ड्राइवर की प्रतिक्रिया का इंतज़ार',
            ta: 'டிரைவரின் பதிலை காத்திருக்கிறோம்',
            te: 'డ్రైవర్ల స్పందన కోసం చూస్తున్నాం',
            bn: 'ড্রাইভারের উত্তর আসার অপেক্ষা',
            ml: 'ഡ്രൈവറിന്റെ പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു',
            od: 'ଡ୍ରାଇଭରଙ୍କ ପ୍ରତିକ୍ରିୟା ଅପେକ୍ଷା କରୁଛୁ',
            nl: 'Wachten op reactie van chauffeur',
            de: 'Warten auf Fahrerantwort',
            fr: 'En attente de la réponse du chauffeur',
            fi: 'Odotetaan kuljettajan vastausta',
            sv: 'Väntar på förarens svar',
            gu: 'ડ્રાઇવરના જવાબની રાહ જોઈ રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Almost there, hold on',
            kn: 'ಇನ್ನು ಸ್ವಲ್ಪವೇ, ದಯವಿಟ್ಟು ಕಾಯಿರಿ',
            hi: 'थोड़ा इंतज़ार करें, बस हो गया',
            ta: 'சிறிது நேரம் காத்திருக்கவும்',
            te: 'ఇంకాసేపు ఆగండి, కాబోతుంది',
            bn: 'আরও কিছুক্ষণ অপেক্ষা করুন',
            ml: 'കുറച്ച് നേരം കാത്തിരിക്കുക',
            od: 'ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ',
            nl: 'Bijna daar, even geduld',
            de: 'Fast da, bitte warten',
            fr: 'Presque là, patientez',
            fi: 'Melkein valmista, odota hetki',
            sv: 'Nästan klart, vänta ett ögonblick',
            gu: 'લગભગ થઈ ગયું, રાહ જુઓ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Looking for all available drivers',
            kn: 'ಲಭ್ಯವಿರುವ ಎಲ್ಲ ಚಾಲಕರನ್ನು ಹುಡುಕುತ್ತಿದ್ದೇವೆ',
            hi: 'सभी उपलब्ध ड्राइवरों को खोज रहे हैं',
            ta: 'அனைத்து கிடைக்கும் டிரைவர்களையும் தேடுகிறோம்',
            te: 'అందుబాటులో ఉన్న అన్ని డ్రైవర్లను వెతుకుతున్నాం',
            bn: 'সকল উপলব্ধ ড্রাইভার খোঁজা হচ্ছে',
            ml: 'എല്ലാ ലഭ്യമായ ഡ്രൈവർമാരെയും അന്വേഷിക്കുന്നു',
            od: 'ସମସ୍ତ ଉପଲବ୍ଧ ଡ୍ରାଇଭରଙ୍କୁ ଖୋଜୁଛୁ',
            nl: 'Zoeken naar alle beschikbare chauffeurs',
            de: 'Suche nach allen verfügbaren Fahrern',
            fr: 'Recherche de tous les chauffeurs disponibles',
            fi: 'Etsitään kaikkia saatavilla olevia kuljettajia',
            sv: 'Letar efter alla tillgängliga förare',
            gu: 'બધા ઉપલબ્ધ ડ્રાઇવરો શોધી રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Request sent to drivers',
            kn: 'ಚಾಲಕರಿಗೆ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ',
            hi: 'ड्राइवरों को अनुरोध भेजा गया',
            ta: 'டிரைவர்களுக்கு கோரிக்கை அனுப்பப்பட்டது',
            te: 'డ్రైవర్లకు అభ్యర్థన పంపాం',
            bn: 'ড্রাইভারদের অনুরোধ পাঠানো হয়েছে',
            ml: 'ഡ്രൈവർമാർക്ക് അഭ്യർത്ഥന അയച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ କୁ ଅନୁରୋଧ ପଠାଯାଇଛି',
            nl: 'Verzoek verzonden naar chauffeurs',
            de: 'Anfrage an Fahrer gesendet',
            fr: 'Demande envoyée aux chauffeurs',
            fi: 'Pyyntö lähetetty kuljettajille',
            sv: 'Förfrågan skickad till förare',
            gu: 'ડ્રાઇવરોને વિનંતી મોકલી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Drivers received your request',
            kn: 'ಚಾಲಕರಿಗೆ ನಿಮ್ಮ ವಿನಂತಿ ಸಿಕ್ಕಿದೆ',
            hi: 'ड्राइवरों को आपका अनुरोध मिला',
            ta: 'டிரைவர்களுக்கு உங்கள் கோரிக்கை வந்தது',
            te: 'డ్రైవర్లకు మీ అభ్యర్థన చేరింది',
            bn: 'ড্রাইভাররা আপনার অনুরোধ পেয়েছে',
            ml: 'ഡ്രൈവർമാർ നിങ്ങളുടെ അഭ്യർത്ഥന സ്വീകരിച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ ଆପଣଙ୍କ ଅନୁରୋଧ ଦେଖିଛନ୍ତି',
            nl: 'Chauffeurs hebben uw verzoek ontvangen',
            de: 'Fahrer haben Ihre Anfrage erhalten',
            fr: 'Les chauffeurs ont reçu votre demande',
            fi: 'Kuljettajat saivat pyyntösi',
            sv: 'Förare fick din förfrågan',
            gu: 'ડ્રાઇવરોને તમારી વિનંતી મળી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Awaiting driver response',
            kn: 'ಚಾಲಕರ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಕಾಯುತ್ತಿದ್ದೇವೆ',
            hi: 'ड्राइवर की प्रतिक्रिया का इंतज़ार',
            ta: 'டிரைவரின் பதிலை காத்திருக்கிறோம்',
            te: 'డ్రైవర్ల స్పందన కోసం చూస్తున్నాం',
            bn: 'ড্রাইভারের উত্তর আসার অপেক্ষা',
            ml: 'ഡ്രൈവറിന്റെ പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു',
            od: 'ଡ୍ରାଇଭରଙ୍କ ପ୍ରତିକ୍ରିୟା ଅପେକ୍ଷା କରୁଛୁ',
            nl: 'Wachten op reactie van chauffeur',
            de: 'Warten auf Fahrerantwort',
            fr: 'En attente de la réponse du chauffeur',
            fi: 'Odotetaan kuljettajan vastausta',
            sv: 'Väntar på förarens svar',
            gu: 'ડ્રાઇવરના જવાબની રાહ જોઈ રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Final check with drivers',
            kn: 'ಚಾಲಕರೊಂದಿಗೆ ಕೊನೆಯ ಬಾರಿ ಪರಿಶೀಲನೆ',
            hi: 'ड्राइवरों से अंतिम बार पूछ रहे हैं',
            ta: 'டிரைவர்களுடன் கடைசி முறையாக சரிபார்க்கிறோம்',
            te: 'చివరిసారి డ్రైవర్లను పరిశీలిస్తున్నాం',
            bn: 'শেষবার ড্রাইভারদের জিজ্ঞাসা করছি',
            ml: 'അവസാനമായി ഡ്രൈവർമാരെ പരിശോധിക്കുന്നു',
            od: 'ଶେଷ ଥର ପାଇଁ ଡ୍ରାଇଭରମାନେ ସହିତ ଯାଞ୍ଚ କରୁଛୁ',
            nl: 'Laatste controle bij chauffeurs',
            de: 'Letzte Überprüfung bei Fahrern',
            fr: 'Vérification finale avec les chauffeurs',
            fi: 'Viimeinen tarkistus kuljettajien kanssa',
            sv: 'Sista kontrollen med förare',
            gu: 'ડ્રાઇવરો સાથે અંતિમ તપાસ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Request sent to drivers',
            kn: 'ಚಾಲಕರಿಗೆ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ',
            hi: 'ड्राइवरों को अनुरोध भेजा गया',
            ta: 'டிரைவர்களுக்கு கோரிக்கை அனுப்பப்பட்டது',
            te: 'డ్రైవర్లకు అభ్యర్థన పంపాం',
            bn: 'ড্রাইভারদের অনুরোধ পাঠানো হয়েছে',
            ml: 'ഡ്രൈവർമാർക്ക് അഭ്യർത്ഥന അയച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ କୁ ଅନୁରୋଧ ପଠାଯାଇଛି',
            nl: 'Verzoek verzonden naar chauffeurs',
            de: 'Anfrage an Fahrer gesendet',
            fr: 'Demande envoyée aux chauffeurs',
            fi: 'Pyyntö lähetetty kuljettajille',
            sv: 'Förfrågan skickad till förare',
            gu: 'ડ્રાઇવરોને વિનંતી મોકલી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Drivers received your request',
            kn: 'ಚಾಲಕರಿಗೆ ನಿಮ್ಮ ವಿನಂತಿ ಸಿಕ್ಕಿದೆ',
            hi: 'ड्राइवरों को आपका अनुरोध मिला',
            ta: 'டிரைவர்களுக்கு உங்கள் கோரிக்கை வந்தது',
            te: 'డ్రైవర్లకు మీ అభ్యర్థన చేరింది',
            bn: 'ড্রাইভাররা আপনার অনুরোধ পেয়েছে',
            ml: 'ഡ്രൈവർമാർ നിങ്ങളുടെ അഭ്യർത്ഥന സ്വീകരിച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ ଆପଣଙ୍କ ଅନୁରୋଧ ଦେଖିଛନ୍ତି',
            nl: 'Chauffeurs hebben uw verzoek ontvangen',
            de: 'Fahrer haben Ihre Anfrage erhalten',
            fr: 'Les chauffeurs ont reçu votre demande',
            fi: 'Kuljettajat saivat pyyntösi',
            sv: 'Förare fick din förfrågan',
            gu: 'ડ્રાઇવરોને તમારી વિનંતી મળી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Awaiting driver response',
            kn: 'ಚಾಲಕರ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಕಾಯುತ್ತಿದ್ದೇವೆ',
            hi: 'ड्राइवर की प्रतिक्रिया का इंतज़ार',
            ta: 'டிரைவரின் பதிலை காத்திருக்கிறோம்',
            te: 'డ్రైవర్ల స్పందన కోసం చూస్తున్నాం',
            bn: 'ড্রাইভারের উত্তর আসার অপেক্ষা',
            ml: 'ഡ്രൈവറിന്റെ പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു',
            od: 'ଡ୍ରାଇଭରଙ୍କ ପ୍ରତିକ୍ରିୟା ଅପେକ୍ଷା କରୁଛୁ',
            nl: 'Wachten op reactie van chauffeur',
            de: 'Warten auf Fahrerantwort',
            fr: 'En attente de la réponse du chauffeur',
            fi: 'Odotetaan kuljettajan vastausta',
            sv: 'Väntar på förarens svar',
            gu: 'ડ્રાઇવરના જવાબની રાહ જોઈ રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Hang tight, finding drivers',
            kn: 'ದಯವಿಟ್ಟು ಕಾಯಿರಿ, ಚಾಲಕರನ್ನು ಹುಡುಕುತ್ತಿದ್ದೇವೆ',
            hi: 'थोड़ा रुकिए, ड्राइवर खोज रहे हैं',
            ta: 'சிறிது பொறு, டிரைவர்களை தேடுகிறோம்',
            te: 'కాసేపు ఆగండి, డ్రైవర్లను వెతుకుతున్నాం',
            bn: 'অপেক্ষা করুন, ড্রাইভার খুঁজছি',
            ml: 'കാത്തിരിക്കുക, ഡ്രൈവർമാരെ തിരയുന്നു',
            od: 'ଅପେକ୍ଷା କରନ୍ତୁ, ଡ୍ରାଇଭର ଖୋଜୁଛୁ',
            nl: 'Even wachten, chauffeurs zoeken',
            de: 'Warten Sie, suche Fahrer',
            fr: 'Patientez, recherche de chauffeurs',
            fi: 'Odota hetki, etsitään kuljettajia',
            sv: 'Vänta ett ögonblick, letar efter förare',
            gu: 'રાહ જુઓ, ડ્રાઇવરો શોધી રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Request sent to drivers',
            kn: 'ಚಾಲಕರಿಗೆ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ',
            hi: 'ड्राइवरों को अनुरोध भेजा गया',
            ta: 'டிரைவர்களுக்கு கோரிக்கை அனுப்பப்பட்டது',
            te: 'డ్రైవర్లకు అభ్యర్థన పంపాం',
            bn: 'ড্রাইভারদের অনুরোধ পাঠানো হয়েছে',
            ml: 'ഡ്രൈവർമാർക്ക് അഭ്യർത്ഥന അയച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ କୁ ଅନୁରୋଧ ପଠାଯାଇଛି',
            nl: 'Verzoek verzonden naar chauffeurs',
            de: 'Anfrage an Fahrer gesendet',
            fr: 'Demande envoyée aux chauffeurs',
            fi: 'Pyyntö lähetetty kuljettajille',
            sv: 'Förfrågan skickad till förare',
            gu: 'ડ્રાઇવરોને વિનંતી મોકલી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Drivers received your request',
            kn: 'ಚಾಲಕರಿಗೆ ನಿಮ್ಮ ವಿನಂತಿ ಸಿಕ್ಕಿದೆ',
            hi: 'ड्राइवरों को आपका अनुरोध मिला',
            ta: 'டிரைவர்களுக்கு உங்கள் கோரிக்கை வந்தது',
            te: 'డ్రైవర్లకు మీ అభ్యర్థన చేరింది',
            bn: 'ড্রাইভাররা আপনার অনুরোধ পেয়েছে',
            ml: 'ഡ്രൈവർമാർ നിങ്ങളുടെ അഭ്യർത്ഥന സ്വീകരിച്ചു',
            od: 'ଡ୍ରାଇଭରମାନେ ଆପଣଙ୍କ ଅନୁରୋଧ ଦେଖିଛନ୍ତି',
            nl: 'Chauffeurs hebben uw verzoek ontvangen',
            de: 'Fahrer haben Ihre Anfrage erhalten',
            fr: 'Les chauffeurs ont reçu votre demande',
            fi: 'Kuljettajat saivat pyyntösi',
            sv: 'Förare fick din förfrågan',
            gu: 'ડ્રાઇવરોને તમારી વિનંતી મળી',
        },
        zoomLevel: 18.0,
    },
    {
        duration: 6,
        texts: {
            en: 'Awaiting driver response',
            kn: 'ಚಾಲಕರ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಕಾಯುತ್ತಿದ್ದೇವೆ',
            hi: 'ड्राइवर की प्रतिक्रिया का इंतज़ार',
            ta: 'டிரைவரின் பதிலை காத்திருக்கிறோம்',
            te: 'డ్రైవర్ల స్పందన కోసం చూస్తున్నాం',
            bn: 'ড্রাইভারের উত্তর আসার অপেক্ষা',
            ml: 'ഡ്രൈവറിന്റെ പ്രതികരണത്തിനായി കാത്തിരിക്കുന്നു',
            od: 'ଡ୍ରାଇଭରଙ୍କ ପ୍ରତିକ୍ରିୟା ଅପେକ୍ଷା କରୁଛୁ',
            nl: 'Wachten op reactie van chauffeur',
            de: 'Warten auf Fahrerantwort',
            fr: 'En attente de la réponse du chauffeur',
            fi: 'Odotetaan kuljettajan vastausta',
            sv: 'Väntar på förarens svar',
            gu: 'ડ્રાઇવરના જવાબની રાહ જોઈ રહ્યા છીએ',
        },
        zoomLevel: 18.0,
    },
];

export const defaultBoostedRotatingTextConfig = {
    bangalore: defaultConfig,
    mumbai: defaultConfig,
    delhi: defaultConfig,
    chennai: defaultConfig,
    kolkata: defaultConfig,
    paris: defaultConfig,
    kochi: defaultConfig,
    hyderabad: defaultConfig,
    coimbatore: defaultConfig,
    pondicherry: defaultConfig,
    goa: defaultConfig,
    pune: defaultConfig,
    mysore: defaultConfig,
    tumakuru: defaultConfig,
    noida: defaultConfig,
    gurugram: defaultConfig,
    siliguri: defaultConfig,
    asansol: defaultConfig,
    durgapur: defaultConfig,
    petrapole: defaultConfig,
    trivandrum: defaultConfig,
    thrissur: defaultConfig,
    kozhikode: defaultConfig,
    vellore: defaultConfig,
    hosur: defaultConfig,
    madurai: defaultConfig,
    thanjavur: defaultConfig,
    tirunelveli: defaultConfig,
    salem: defaultConfig,
    trichy: defaultConfig,
    davanagere: defaultConfig,
    shivamogga: defaultConfig,
    hubli: defaultConfig,
    mangalore: defaultConfig,
    gulbarga: defaultConfig,
    udupi: defaultConfig,
    bhubaneswar: defaultConfig,
    tamilnaducities: defaultConfig,
    ysCities: defaultConfig,
    cuttack: defaultConfig,
    puri: defaultConfig,
    alapuzha: defaultConfig,
    idukki: defaultConfig,
    kasarkode: defaultConfig,
    wayanad: defaultConfig,
    kannur: defaultConfig,
    kottayam: defaultConfig,
    palakkad: defaultConfig,
    kolam: defaultConfig,
    default: defaultConfig,
    minneapolis: defaultConfig,
    chandigarh: defaultConfig,
    jaipur: defaultConfig,
    gangtok: defaultConfig,
    darjeeling: defaultConfig,
    vijayawada: defaultConfig,
    vishakapatnam: defaultConfig,
    guntur: defaultConfig,
    tirupati: defaultConfig,
    kurnool: defaultConfig,
    khammam: defaultConfig,
    karimnagar: defaultConfig,
    nizamabad: defaultConfig,
    mahbubnagar: defaultConfig,
    suryapet: defaultConfig,
    nalgonda: defaultConfig,
    siddipet: defaultConfig,
    rourkela: defaultConfig,
    warangal: defaultConfig,
    pudukkottai: defaultConfig,
    bidar: defaultConfig,
    srinagar: defaultConfig,
    pathanamthitta: defaultConfig,
    shillong: defaultConfig,
    cherrapunji: defaultConfig,
    pulwama: defaultConfig,
    jammu: defaultConfig,
    anantnag: defaultConfig,
    berhampur: defaultConfig,
    sambalpur: defaultConfig,
    bardhaman: defaultConfig,
    ballari: defaultConfig,
    amsterdam: defaultConfig,
    digha: defaultConfig,
    rajkot: defaultConfig,
    somnath: defaultConfig,
    dwarka: defaultConfig,
    ahmedabad: defaultConfig,
    surat: defaultConfig,
    vadodara: defaultConfig,
    jamnagar: defaultConfig,
    birbhum: defaultConfig,
};
