import { ReferralPayoutConfigV2 } from '@/src-v2/systems/configs/types';
import { City } from 'config-types';

const defaultReferralPayoutConfig: ReferralPayoutConfigV2 = {
    enable: false,
    youGet: 50,
    theyGet: 50,
    coverImage: 'https://assets.moving.tech/beckn/common/user/images/ny_ic_referral_r2r_cover_1.png',
    modalImage:
        'https://raw.githubusercontent.com/witcher-shailesh/github-asset-store/main/uploads/referral/img-mt_ic_apply_referral.webp',
    termsLink: 'https://docs.google.com/document/d/1ZkgiluudQnYiFWlMNEZ18owFdkz_LqDr',
};

export const defaultReferralPayoutConfigV2: Record<City, ReferralPayoutConfigV2> = {
    bangalore: defaultReferralPayoutConfig,
    mumbai: defaultReferralPayoutConfig,
    delhi: defaultReferralPayoutConfig,
    chennai: defaultReferralPayoutConfig,
    kolkata: defaultReferralPayoutConfig,
    paris: defaultReferralPayoutConfig,
    kochi: defaultReferralPayoutConfig,
    hyderabad: defaultReferralPayoutConfig,
    coimbatore: defaultReferralPayoutConfig,
    pondicherry: defaultReferralPayoutConfig,
    goa: defaultReferralPayoutConfig,
    pune: defaultReferralPayoutConfig,
    mysore: defaultReferralPayoutConfig,
    tumakuru: defaultReferralPayoutConfig,
    noida: defaultReferralPayoutConfig,
    gurugram: defaultReferralPayoutConfig,
    siliguri: defaultReferralPayoutConfig,
    asansol: defaultReferralPayoutConfig,
    durgapur: defaultReferralPayoutConfig,
    petrapole: defaultReferralPayoutConfig,
    trivandrum: defaultReferralPayoutConfig,
    thrissur: defaultReferralPayoutConfig,
    kozhikode: defaultReferralPayoutConfig,
    vellore: defaultReferralPayoutConfig,
    hosur: defaultReferralPayoutConfig,
    madurai: defaultReferralPayoutConfig,
    thanjavur: defaultReferralPayoutConfig,
    tirunelveli: defaultReferralPayoutConfig,
    salem: defaultReferralPayoutConfig,
    trichy: defaultReferralPayoutConfig,
    davanagere: defaultReferralPayoutConfig,
    shivamogga: defaultReferralPayoutConfig,
    hubli: defaultReferralPayoutConfig,
    mangalore: defaultReferralPayoutConfig,
    gulbarga: defaultReferralPayoutConfig,
    udupi: defaultReferralPayoutConfig,
    bhubaneswar: defaultReferralPayoutConfig,
    tamilnaducities: defaultReferralPayoutConfig,
    ysCities: defaultReferralPayoutConfig,
    cuttack: defaultReferralPayoutConfig,
    puri: defaultReferralPayoutConfig,
    alapuzha: defaultReferralPayoutConfig,
    idukki: defaultReferralPayoutConfig,
    kasarkode: defaultReferralPayoutConfig,
    wayanad: defaultReferralPayoutConfig,
    kannur: defaultReferralPayoutConfig,
    kottayam: defaultReferralPayoutConfig,
    palakkad: defaultReferralPayoutConfig,
    kolam: defaultReferralPayoutConfig,
    default: defaultReferralPayoutConfig,
    minneapolis: defaultReferralPayoutConfig,
    chandigarh: defaultReferralPayoutConfig,
    jaipur: defaultReferralPayoutConfig,
    gangtok: defaultReferralPayoutConfig,
    darjeeling: defaultReferralPayoutConfig,
    vijayawada: defaultReferralPayoutConfig,
    vishakapatnam: defaultReferralPayoutConfig,
    guntur: defaultReferralPayoutConfig,
    tirupati: defaultReferralPayoutConfig,
    kurnool: defaultReferralPayoutConfig,
    khammam: defaultReferralPayoutConfig,
    karimnagar: defaultReferralPayoutConfig,
    nizamabad: defaultReferralPayoutConfig,
    mahbubnagar: defaultReferralPayoutConfig,
    suryapet: defaultReferralPayoutConfig,
    nalgonda: defaultReferralPayoutConfig,
    siddipet: defaultReferralPayoutConfig,
    rourkela: defaultReferralPayoutConfig,
    warangal: defaultReferralPayoutConfig,
    pudukkottai: defaultReferralPayoutConfig,
    bidar: defaultReferralPayoutConfig,
    srinagar: defaultReferralPayoutConfig,
    pathanamthitta: defaultReferralPayoutConfig,
    shillong: defaultReferralPayoutConfig,
    cherrapunji: defaultReferralPayoutConfig,
    pulwama: defaultReferralPayoutConfig,
    jammu: defaultReferralPayoutConfig,
    anantnag: defaultReferralPayoutConfig,
    berhampur: defaultReferralPayoutConfig,
    sambalpur: defaultReferralPayoutConfig,
    bardhaman: defaultReferralPayoutConfig,
    ballari: defaultReferralPayoutConfig,
    amsterdam: defaultReferralPayoutConfig,
    digha: defaultReferralPayoutConfig,
    rajkot: defaultReferralPayoutConfig,
    somnath: defaultReferralPayoutConfig,
    dwarka: defaultReferralPayoutConfig,
    ahmedabad: defaultReferralPayoutConfig,
    surat: defaultReferralPayoutConfig,
    vadodara: defaultReferralPayoutConfig,
    jamnagar: defaultReferralPayoutConfig,
    birbhum: defaultReferralPayoutConfig,
};
