import { City } from 'config-types';
import { HomescreenModules } from '../types';

const defaulConfig: HomescreenModules[] = [
    'NAMMA_SERVICES',
    'BANNERS',
    'HOURLY_RENTALS',
    'INTERCITY_RECOMMENDATIONS',
    'NEARBY_EVENTS',
    'EXPLORE',
];

export const defaultHomeScreenModulesConfig: Record<City, HomescreenModules[]> = {
    bangalore: defaulConfig,
    mumbai: defaulConfig,
    delhi: defaulConfig,
    chennai: defaulConfig,
    kolkata: defaulConfig,
    paris: defaulConfig,
    kochi: defaulConfig,
    hyderabad: defaulConfig,
    coimbatore: defaulConfig,
    pondicherry: defaulConfig,
    goa: defaulConfig,
    pune: defaulConfig,
    mysore: defaulConfig,
    tumakuru: defaulConfig,
    noida: defaulConfig,
    gurugram: defaulConfig,
    siliguri: defaulConfig,
    asansol: defaulConfig,
    durgapur: defaulConfig,
    petrapole: defaulConfig,
    trivandrum: defaulConfig,
    thrissur: defaulConfig,
    kozhikode: defaulConfig,
    vellore: defaulConfig,
    hosur: defaulConfig,
    madurai: defaulConfig,
    thanjavur: defaulConfig,
    tirunelveli: defaulConfig,
    salem: defaulConfig,
    trichy: defaulConfig,
    davanagere: defaulConfig,
    shivamogga: defaulConfig,
    hubli: defaulConfig,
    mangalore: defaulConfig,
    gulbarga: defaulConfig,
    udupi: defaulConfig,
    bhubaneswar: defaulConfig,
    tamilnaducities: defaulConfig,
    ysCities: defaulConfig,
    cuttack: defaulConfig,
    puri: defaulConfig,
    alapuzha: defaulConfig,
    idukki: defaulConfig,
    kasarkode: defaulConfig,
    wayanad: defaulConfig,
    kannur: defaulConfig,
    kottayam: defaulConfig,
    palakkad: defaulConfig,
    kolam: defaulConfig,
    default: defaulConfig,
    minneapolis: defaulConfig,
    chandigarh: defaulConfig,
    jaipur: defaulConfig,
    gangtok: defaulConfig,
    darjeeling: defaulConfig,
    vijayawada: defaulConfig,
    vishakapatnam: defaulConfig,
    guntur: defaulConfig,
    tirupati: defaulConfig,
    kurnool: defaulConfig,
    khammam: defaulConfig,
    karimnagar: defaulConfig,
    nizamabad: defaulConfig,
    mahbubnagar: defaulConfig,
    suryapet: defaulConfig,
    nalgonda: defaulConfig,
    siddipet: defaulConfig,
    rourkela: defaulConfig,
    warangal: defaulConfig,
    pudukkottai: defaulConfig,
    bidar: defaulConfig,
    srinagar: defaulConfig,
    pathanamthitta: defaulConfig,
    shillong: defaulConfig,
    cherrapunji: defaulConfig,
    pulwama: defaulConfig,
    jammu: defaulConfig,
    anantnag: defaulConfig,
    berhampur: defaulConfig,
    sambalpur: defaulConfig,
    bardhaman: defaulConfig,
    ballari: defaulConfig,
    amsterdam: defaulConfig,
    digha: defaulConfig,
    rajkot: defaulConfig,
    somnath: defaulConfig,
    dwarka: defaulConfig,
    ahmedabad: defaulConfig,
    surat: defaulConfig,
    vadodara: defaulConfig,
    jamnagar: defaulConfig,
    birbhum: defaulConfig,
};
