import { City } from 'config-types';
import { skipAndStartJourneyConfig } from '../types';

const defaultConfig: skipAndStartJourneyConfig = {
    text: [
        {
            text: 'start Your journey without booking a ticket up front',
            iconUrl: 'https://example.com/bangalore_icon1.png',
        },
        {
            text: 'Book metro after your first mile get sorted',
            iconUrl: 'https://example.com/bangalore_icon2.png',
        },
        {
            text: 'Book anytime before starting the metro leg tracking',
            iconUrl: 'https://example.com/bangalore_icon3.png',
        },
        {
            text: 'Stay updated with live status',
            iconUrl: 'https://example.com/bangalore_icon4.png',
        },
    ],
    illustration_url: 'https://example.com/bangalore_illustration.png',
    information_button_url: 'https://example.com/bangalore-info-button-url',
};

export const defaultSkipAndStartJourneyConfig: Record<City, skipAndStartJourneyConfig> = {
    bangalore: defaultConfig,
    mumbai: defaultConfig,
    delhi: defaultConfig,
    chennai: defaultConfig,
    kolkata: defaultConfig,
    paris: defaultConfig,
    kochi: defaultConfig,
    hyderabad: defaultConfig,
    coimbatore: defaultConfig,
    pondicherry: defaultConfig,
    goa: defaultConfig,
    pune: defaultConfig,
    mysore: defaultConfig,
    tumakuru: defaultConfig,
    noida: defaultConfig,
    gurugram: defaultConfig,
    siliguri: defaultConfig,
    asansol: defaultConfig,
    durgapur: defaultConfig,
    petrapole: defaultConfig,
    trivandrum: defaultConfig,
    thrissur: defaultConfig,
    kozhikode: defaultConfig,
    vellore: defaultConfig,
    hosur: defaultConfig,
    madurai: defaultConfig,
    thanjavur: defaultConfig,
    tirunelveli: defaultConfig,
    salem: defaultConfig,
    trichy: defaultConfig,
    davanagere: defaultConfig,
    shivamogga: defaultConfig,
    hubli: defaultConfig,
    mangalore: defaultConfig,
    gulbarga: defaultConfig,
    udupi: defaultConfig,
    bhubaneswar: defaultConfig,
    tamilnaducities: defaultConfig,
    ysCities: defaultConfig,
    cuttack: defaultConfig,
    puri: defaultConfig,
    alapuzha: defaultConfig,
    idukki: defaultConfig,
    kasarkode: defaultConfig,
    wayanad: defaultConfig,
    kannur: defaultConfig,
    kottayam: defaultConfig,
    palakkad: defaultConfig,
    kolam: defaultConfig,
    minneapolis: defaultConfig,
    chandigarh: defaultConfig,
    jaipur: defaultConfig,
    gangtok: defaultConfig,
    darjeeling: defaultConfig,
    vijayawada: defaultConfig,
    vishakapatnam: defaultConfig,
    guntur: defaultConfig,
    tirupati: defaultConfig,
    kurnool: defaultConfig,
    khammam: defaultConfig,
    karimnagar: defaultConfig,
    nizamabad: defaultConfig,
    mahbubnagar: defaultConfig,
    suryapet: defaultConfig,
    nalgonda: defaultConfig,
    siddipet: defaultConfig,
    rourkela: defaultConfig,
    warangal: defaultConfig,
    pudukkottai: defaultConfig,
    bidar: defaultConfig,
    srinagar: defaultConfig,
    pathanamthitta: defaultConfig,
    shillong: defaultConfig,
    cherrapunji: defaultConfig,
    pulwama: defaultConfig,
    jammu: defaultConfig,
    anantnag: defaultConfig,
    berhampur: defaultConfig,
    sambalpur: defaultConfig,
    bardhaman: defaultConfig,
    ballari: defaultConfig,
    amsterdam: defaultConfig,
    digha: defaultConfig,
    rajkot: defaultConfig,
    somnath: defaultConfig,
    dwarka: defaultConfig,
    ahmedabad: defaultConfig,
    surat: defaultConfig,
    vadodara: defaultConfig,
    jamnagar: defaultConfig,
    birbhum: defaultConfig,
    default: defaultConfig,
};
