import { City } from 'config-types';
import { newFeatureFlags, VideoBottomSheetConfig } from '../types';

const appLaunchIntroVideoConfig: VideoBottomSheetConfig = {
    id: 'app_launch_video_popup',
    enabled: false,
    showOnLaunch: true,
    frequency: 'always',
    showDelayMs: 2000,
    media: {
        type: 'video',
        url: 'https://raw.githubusercontent.com/witcher-shailesh/github-asset-store/main/uploads/vids/intro-design.mp4',
        fallbackImageUrl: 'namma_transit_buffer.webp',
        autoPlay: true,
        shouldLoop: true,
        muted: true,
        videoPlayerConfig: {
            enableNetworkOptimizations: true,
            bufferingDelay: 1000,
            networkOptimizationConfig: {
                minBufferMs: 3000,
                maxBufferMs: 15000,
                bufferForPlaybackMs: 1000,
                bufferForPlaybackAfterRebufferMs: 2000,
            },
        },
        lottieConfig: undefined,
    },
    title: 'Introducing Namma Transit',
    buttonText: 'Try Now',
    resizeMode: 'contain',
    icons: undefined,
    onButtonPress: {
        actionName: 'navigateToStage',
        actionData: 'Search',
    },
};

const nammaTransitServicePopupConfig: VideoBottomSheetConfig = {
    id: 'namma_transit_service_button_popup',
    enabled: true,
    showOnLaunch: false,
    frequency: 'disabled',
    showDelayMs: 0,
    media: {
        type: 'video',
        url: 'https://raw.githubusercontent.com/witcher-shailesh/github-asset-store/main/uploads/vids/intro-design.mp4',
        fallbackImageUrl: 'namma_transit_buffer.webp',
        autoPlay: true,
        shouldLoop: true,
        muted: true,
        videoPlayerConfig: {
            enableNetworkOptimizations: true,
            bufferingDelay: 1000,
            networkOptimizationConfig: {
                minBufferMs: 3000,
                maxBufferMs: 15000,
                bufferForPlaybackMs: 1000,
                bufferForPlaybackAfterRebufferMs: 2000,
            },
        },
        lottieConfig: undefined,
    },
    title: 'Auto + Public Transport to make your journey quick & affordable',
    buttonText: 'Try Transit',
    resizeMode: 'contain',
    icons: {
        leftIcon: {
            component: 'AutoIcon',
            backgroundColor: '#E1D4F8',
            iconColor: '#470F2D',
        },
        rightIcon: {
            component: 'MetroIcon',
            backgroundColor: '#CCE6F6',
            iconColor: '#1F2D3D',
        },
        showPlusSign: true,
    },
    onButtonPress: undefined,
};

const defaultFeatureFlags: newFeatureFlags = {
    version: '0.0.1',
    enableLocationUnserviceable: false,
    toggleQRtoOtpFlow: true,
    preSelectedSmartTip: false,
    enableGreeting: false,
    slowNetworkToastThreshHold: 4000,
    appUpdateMethod: 'ignore_update',
    estimatesTipEnabled: false,
    lookingForRidesTipEnabled: false,
    pickupThresholdForReallocation: 50,
    shouldShowDefaultTips: false,
    feedbackPendingExpiryTimeInMs: 172800000,
    editTipOrVehicleButtonDisableThreshold: 15000,
    boostedSearchModalOpenTime: 15000,
    enableTrueCaller: true,
    enablePetRide: false,
    showInsurancePolicy: false,
    enableWhatsappOTPLogin: false,
    enableDriverFavourite: true,
    enableMultimodal: true,
    enableHyperUPI: false,
    customerCancellationConfig: {
        enableCancellationCharges: false,
        cancellationStaggerPct: 0,
        noChargeImgA: 'https://raw.githubusercontent.com/witcher-shailesh/github-asset-store/main/uploads/warning.png',
        noChargeImgB: 'https://raw.githubusercontent.com/witcher-shailesh/github-asset-store/main/uploads/empathy.png',
        img_a: 'https://raw.githubusercontent.com/witcher-shailesh/github-asset-store/main/uploads/warning.png',
        img_auto: 'https://raw.githubusercontent.com/witcher-shailesh/github-asset-store/main/uploads/empathy.png',
        img_cab: 'https://raw.githubusercontent.com/witcher-shailesh/github-asset-store/main/uploads/empathy.png',
        img_bike: 'https://raw.githubusercontent.com/witcher-shailesh/github-asset-store/main/uploads/empathy.png',
    },
    enableSourceStopsSlicing: false,
    transitOptions: {
        showMoreRoutes: false,
        showPublicTransitPreferences: false,
    },
    showPublicTransportAboveEstimates: false,
    showSeparateNammaTransit: false,
    estimateCardsPositionConfig: {
        nammaTransitPosition: 2,
        bookAnyPosition: 5,
        ambulanceServicePosition: 2,
    },
    showBetaTag: true,
    enablePickupInstructions: false,
    enablePickupInstructionsNewPill: false,
    pickupInstructionsMaxEditCount: 2,
    enableKaptureHelpSupport: false,
    pickupInstructionsCharLimit: 60,
    audioRecordingTimeLimit: 15,
    multimodalTicketConfig: {
        dynamicRefresh: false,
        refreshTime: 30000,
    },
    enableAddStop: false,
    toleranceForGroupingTimeSegments: 3,
    bufferMinutesForCurrentSegment: 5,
    showNammaTransitOnTop: false,
    appLaunchPopupConfig: appLaunchIntroVideoConfig,
    nammaTransitServicePopupConfig: { ...nammaTransitServicePopupConfig, enabled: false },
    multimodalTrackWithoutBooking: true,
    enableUserRateCard: true,
    skipUpdateProfileOnboarding: false,
    identifyBusPollingTime: 2000,
    attractionTicketingNotes: [],
    singleModeBusSearchBarAnimationDuration: 30000,
    passEnabled: false,
    autoActivatePass: false,
    showNearbyBusInOtpFlow: false,
    enableCancellationCharges: true,
    showTrainDetailInMyRides: false,
    showOfferTextForBookBtn: false,
    enableDriverPickupETA: false,
    maxDriverPickupETA: 180,
    defaultPassStartDate: 'today',
    enableFindAnotherDriver: true,
    skipFirstLegSingleMode: false,
    farAwayDistanceThresholdKm: 2,
};

const defaultFeatureFlagsNY: newFeatureFlags = {
    ...defaultFeatureFlags,
    nammaTransitServicePopupConfig: nammaTransitServicePopupConfig,
};

export const defaultNewFeatureFlags: Record<City, newFeatureFlags> = {
    bangalore: defaultFeatureFlagsNY,
    mumbai: defaultFeatureFlags,
    delhi: { ...defaultFeatureFlags, enableFindAnotherDriver: false },
    chennai: {
        ...defaultFeatureFlags,
        enableGreeting: true,
        passEnabled: true,
        autoActivatePass: false,
        skipFirstLegSingleMode: true,
    },
    kolkata: { ...defaultFeatureFlags, showInsurancePolicy: true },
    paris: defaultFeatureFlags,
    kochi: defaultFeatureFlags,
    hyderabad: defaultFeatureFlags,
    coimbatore: defaultFeatureFlags,
    pondicherry: defaultFeatureFlags,
    goa: defaultFeatureFlags,
    pune: defaultFeatureFlags,
    mysore: defaultFeatureFlags,
    tumakuru: defaultFeatureFlags,
    noida: { ...defaultFeatureFlags, enableFindAnotherDriver: false },
    gurugram: { ...defaultFeatureFlags, enableFindAnotherDriver: false },
    siliguri: defaultFeatureFlags,
    asansol: defaultFeatureFlags,
    durgapur: defaultFeatureFlags,
    petrapole: defaultFeatureFlags,
    trivandrum: defaultFeatureFlags,
    thrissur: defaultFeatureFlags,
    kozhikode: defaultFeatureFlags,
    vellore: defaultFeatureFlags,
    hosur: defaultFeatureFlags,
    madurai: defaultFeatureFlags,
    thanjavur: defaultFeatureFlags,
    tirunelveli: defaultFeatureFlags,
    salem: defaultFeatureFlags,
    trichy: defaultFeatureFlags,
    davanagere: defaultFeatureFlags,
    shivamogga: defaultFeatureFlags,
    hubli: defaultFeatureFlags,
    mangalore: defaultFeatureFlags,
    gulbarga: defaultFeatureFlags,
    udupi: defaultFeatureFlags,
    bhubaneswar: defaultFeatureFlags,
    tamilnaducities: defaultFeatureFlags,
    ysCities: defaultFeatureFlags,
    cuttack: defaultFeatureFlags,
    puri: defaultFeatureFlags,
    alapuzha: defaultFeatureFlags,
    idukki: defaultFeatureFlags,
    kasarkode: defaultFeatureFlags,
    wayanad: defaultFeatureFlags,
    kannur: defaultFeatureFlags,
    kottayam: defaultFeatureFlags,
    palakkad: defaultFeatureFlags,
    kolam: defaultFeatureFlags,
    default: { ...defaultFeatureFlags, showInsurancePolicy: true },
    minneapolis: defaultFeatureFlags,
    chandigarh: defaultFeatureFlags,
    jaipur: defaultFeatureFlags,
    gangtok: defaultFeatureFlags,
    darjeeling: defaultFeatureFlags,
    vijayawada: defaultFeatureFlags,
    vishakapatnam: defaultFeatureFlags,
    guntur: defaultFeatureFlags,
    tirupati: defaultFeatureFlags,
    kurnool: defaultFeatureFlags,
    khammam: defaultFeatureFlags,
    karimnagar: defaultFeatureFlags,
    nizamabad: defaultFeatureFlags,
    mahbubnagar: defaultFeatureFlags,
    suryapet: defaultFeatureFlags,
    nalgonda: defaultFeatureFlags,
    siddipet: defaultFeatureFlags,
    rourkela: defaultFeatureFlags,
    warangal: defaultFeatureFlags,
    pudukkottai: defaultFeatureFlags,
    bidar: defaultFeatureFlags,
    srinagar: defaultFeatureFlags,
    pathanamthitta: defaultFeatureFlags,
    shillong: defaultFeatureFlags,
    cherrapunji: defaultFeatureFlags,
    pulwama: defaultFeatureFlags,
    jammu: defaultFeatureFlags,
    anantnag: defaultFeatureFlags,
    berhampur: defaultFeatureFlags,
    sambalpur: defaultFeatureFlags,
    bardhaman: defaultFeatureFlags,
    ballari: defaultFeatureFlags,
    amsterdam: defaultFeatureFlags,
    digha: defaultFeatureFlags,
    rajkot: { ...defaultFeatureFlags, enableFindAnotherDriver: false },
    somnath: defaultFeatureFlags,
    dwarka: defaultFeatureFlags,
    ahmedabad: defaultFeatureFlags,
    surat: defaultFeatureFlags,
    vadodara: defaultFeatureFlags,
    jamnagar: defaultFeatureFlags,
    birbhum: defaultFeatureFlags,
};
