import { City } from 'config-types';
import { TabScreensConfig } from '../types';

const standardTabsConfig: TabScreensConfig = {
    tabs: ['HomeTab', 'LiveTab', 'ProfileTab'],
};

const allTabsConfig: TabScreensConfig = {
    tabs: ['HomeTab', 'ServicesTab', 'LiveTab', 'TicketsTab', 'ProfileTab'],
};

export const defaultTabScreensConfig: Record<City, TabScreensConfig> = {
    bangalore: allTabsConfig,
    mumbai: standardTabsConfig,
    delhi: standardTabsConfig,
    chennai: allTabsConfig,
    kolkata: standardTabsConfig,
    paris: standardTabsConfig,
    kochi: standardTabsConfig,
    hyderabad: standardTabsConfig,
    coimbatore: standardTabsConfig,
    pondicherry: standardTabsConfig,
    goa: standardTabsConfig,
    pune: standardTabsConfig,
    mysore: standardTabsConfig,
    tumakuru: standardTabsConfig,
    noida: standardTabsConfig,
    gurugram: standardTabsConfig,
    siliguri: standardTabsConfig,
    asansol: standardTabsConfig,
    durgapur: standardTabsConfig,
    petrapole: standardTabsConfig,
    trivandrum: standardTabsConfig,
    thrissur: standardTabsConfig,
    kozhikode: standardTabsConfig,
    vellore: standardTabsConfig,
    hosur: standardTabsConfig,
    madurai: standardTabsConfig,
    thanjavur: standardTabsConfig,
    tirunelveli: standardTabsConfig,
    salem: standardTabsConfig,
    trichy: standardTabsConfig,
    davanagere: standardTabsConfig,
    shivamogga: standardTabsConfig,
    hubli: standardTabsConfig,
    mangalore: standardTabsConfig,
    gulbarga: standardTabsConfig,
    udupi: standardTabsConfig,
    bhubaneswar: standardTabsConfig,
    tamilnaducities: standardTabsConfig,
    ysCities: standardTabsConfig,
    cuttack: standardTabsConfig,
    puri: standardTabsConfig,
    alapuzha: standardTabsConfig,
    idukki: standardTabsConfig,
    kasarkode: standardTabsConfig,
    wayanad: standardTabsConfig,
    kannur: standardTabsConfig,
    kottayam: standardTabsConfig,
    palakkad: standardTabsConfig,
    kolam: standardTabsConfig,
    minneapolis: standardTabsConfig,
    chandigarh: standardTabsConfig,
    jaipur: standardTabsConfig,
    gangtok: standardTabsConfig,
    darjeeling: standardTabsConfig,
    vijayawada: standardTabsConfig,
    vishakapatnam: standardTabsConfig,
    guntur: standardTabsConfig,
    tirupati: standardTabsConfig,
    kurnool: standardTabsConfig,
    khammam: standardTabsConfig,
    karimnagar: standardTabsConfig,
    nizamabad: standardTabsConfig,
    mahbubnagar: standardTabsConfig,
    suryapet: standardTabsConfig,
    nalgonda: standardTabsConfig,
    siddipet: standardTabsConfig,
    rourkela: standardTabsConfig,
    warangal: standardTabsConfig,
    pudukkottai: standardTabsConfig,
    bidar: standardTabsConfig,
    srinagar: standardTabsConfig,
    pathanamthitta: standardTabsConfig,
    shillong: standardTabsConfig,
    cherrapunji: standardTabsConfig,
    pulwama: standardTabsConfig,
    jammu: standardTabsConfig,
    anantnag: standardTabsConfig,
    berhampur: standardTabsConfig,
    sambalpur: standardTabsConfig,
    bardhaman: standardTabsConfig,
    ballari: standardTabsConfig,
    amsterdam: standardTabsConfig,
    digha: standardTabsConfig,
    rajkot: standardTabsConfig,
    somnath: standardTabsConfig,
    dwarka: standardTabsConfig,
    ahmedabad: standardTabsConfig,
    surat: standardTabsConfig,
    vadodara: standardTabsConfig,
    jamnagar: standardTabsConfig,
    birbhum: standardTabsConfig,
    default: standardTabsConfig,
};
