import { cancellationBannerTexts } from '../types';
import { City } from 'config-types';

const defaultTexts: cancellationBannerTexts = {
    title: {
        en: 'High cancellation rate!',
        hi: 'उच्च रद्दीकरण दर!',
        kn: 'ಹೆಚ್ಚಿನ ರದ್ದತಿ ದರ!',
        ta: 'அதிக ரத்து விகிதம்!',
        te: 'అధిక రద్దు రేటు!',
        bn: 'উচ্চ বাতিল হার!',
        ml: 'ഉയർന്ന റദ്ദാക്കൽ നിരക്ക്!',
        od: 'ଉଚ୍ଚ ବାତିଲ ହାର!',
        nl: 'Hoog annuleringspercentage!',
        de: 'Hohe Stornierungsrate!',
        fr: "Taux d'annulation élevé!",
        fi: 'Korkea peruutusprosentti!',
        sv: 'Hög avbokningsfrekvens!',
        gu: 'ઊંચો રદબાતલ દર!',
    },
    description: {
        en: 'Avoid cancelling to ensure uninterrupted service.',
        hi: 'निर्बाध सेवा सुनिश्चित करने के लिए रद्द करने से बचें।',
        kn: 'ತಡೆರಹಿತ ಸೇವೆಯನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಲು ರದ್ದುಗೊಳಿಸುವುದನ್ನು ತಪ್ಪಿಸಿ.',
        ta: 'தடையற்ற சேவையை உறுதிப்படுத்த ரத்து செய்வதைத் தவிர்க்கவும்.',
        te: 'నిరంతర సేవను నిర్ధారించడానికి రద్దు చేయకుండా ఉండండి.',
        bn: 'নিরবচ্ছিন্ন পরিষেবা নিশ্চিত করতে বাতিল করা এড়িয়ে চলুন।',
        ml: 'തടസ്സമില്ലാത്ത സേവനം ഉറപ്പാക്കാൻ റദ്ദാക്കൽ ഒഴിവാക്കുക.',
        od: 'ନିରବଚ୍ଛିନ୍ନ ସେବା ନିଶ୍ଚିତ କରିବାକୁ ବାତିଲ କରିବା ଠାରୁ ଦୂରେଇ ରୁହନ୍ତୁ।',
        nl: 'Vermijd annuleren om ononderbroken service te garanderen.',
        de: 'Vermeiden Sie Stornierungen, um einen unterbrechungsfreien Service zu gewährleisten.',
        fr: "Évitez d'annuler pour garantir un service ininterrompu.",
        fi: 'Vältä peruutuksia varmistaaksesi keskeytymättömän palvelun.',
        sv: 'Undvik att avboka för att säkerställa oavbruten service.',
        gu: 'નિરંતર સેવા સુનિશ્ચિત કરવા માટે રદ કરવાનું ટાળો.',
    },
};

export const defaultCancellationBannerTexts: Record<City, cancellationBannerTexts> = {
    bangalore: defaultTexts,
    mumbai: defaultTexts,
    delhi: defaultTexts,
    chennai: defaultTexts,
    kolkata: defaultTexts,
    paris: defaultTexts,
    kochi: defaultTexts,
    hyderabad: defaultTexts,
    coimbatore: defaultTexts,
    pondicherry: defaultTexts,
    goa: defaultTexts,
    pune: defaultTexts,
    mysore: defaultTexts,
    tumakuru: defaultTexts,
    noida: defaultTexts,
    gurugram: defaultTexts,
    siliguri: defaultTexts,
    asansol: defaultTexts,
    durgapur: defaultTexts,
    petrapole: defaultTexts,
    trivandrum: defaultTexts,
    thrissur: defaultTexts,
    kozhikode: defaultTexts,
    vellore: defaultTexts,
    hosur: defaultTexts,
    madurai: defaultTexts,
    thanjavur: defaultTexts,
    tirunelveli: defaultTexts,
    salem: defaultTexts,
    trichy: defaultTexts,
    davanagere: defaultTexts,
    shivamogga: defaultTexts,
    hubli: defaultTexts,
    mangalore: defaultTexts,
    gulbarga: defaultTexts,
    udupi: defaultTexts,
    bhubaneswar: defaultTexts,
    cuttack: defaultTexts,
    puri: defaultTexts,
    default: defaultTexts,
    tamilnaducities: defaultTexts,
    ysCities: defaultTexts,
    alapuzha: defaultTexts,
    idukki: defaultTexts,
    kasarkode: defaultTexts,
    wayanad: defaultTexts,
    kannur: defaultTexts,
    kottayam: defaultTexts,
    palakkad: defaultTexts,
    kolam: defaultTexts,
    minneapolis: defaultTexts,
    chandigarh: defaultTexts,
    jaipur: defaultTexts,
    gangtok: defaultTexts,
    darjeeling: defaultTexts,
    vijayawada: defaultTexts,
    vishakapatnam: defaultTexts,
    guntur: defaultTexts,
    tirupati: defaultTexts,
    kurnool: defaultTexts,
    khammam: defaultTexts,
    karimnagar: defaultTexts,
    nizamabad: defaultTexts,
    mahbubnagar: defaultTexts,
    suryapet: defaultTexts,
    nalgonda: defaultTexts,
    siddipet: defaultTexts,
    rourkela: defaultTexts,
    warangal: defaultTexts,
    pudukkottai: defaultTexts,
    bidar: defaultTexts,
    srinagar: defaultTexts,
    pathanamthitta: defaultTexts,
    shillong: defaultTexts,
    cherrapunji: defaultTexts,
    pulwama: defaultTexts,
    jammu: defaultTexts,
    anantnag: defaultTexts,
    berhampur: defaultTexts,
    bardhaman: defaultTexts,
    ballari: defaultTexts,
    amsterdam: defaultTexts,
    digha: defaultTexts,
    rajkot: defaultTexts,
    somnath: defaultTexts,
    dwarka: defaultTexts,
    ahmedabad: defaultTexts,
    surat: defaultTexts,
    vadodara: defaultTexts,
    jamnagar: defaultTexts,
    birbhum: defaultTexts,
    sambalpur: defaultTexts,
};
