import { City } from 'config-types';
import { DriverHighlightConfig } from '@/src-v2/systems/configs/types';

const defaultConfig: DriverHighlightConfig = {
    enabled: false,
    ratingRules: [
        { rating: 5.0, minRideCount: 30 },
        { rating: 4.9, minRideCount: 200 },
        { rating: 4.8, minRideCount: 200 },
        { rating: 4.7, minRideCount: 150 },
    ],
    lowCancellationRate: {
        maxRate: 0.1,
        minRideCount: 100,
    },
    nearbyThresholdMeters: 500,
    experiencedDriverThreshold: 1000,
};

export const defaultDriverHighlightConfig: Record<City, DriverHighlightConfig> = {
    bangalore: defaultConfig,
    mumbai: defaultConfig,
    delhi: defaultConfig,
    chennai: defaultConfig,
    kolkata: defaultConfig,
    paris: defaultConfig,
    kochi: defaultConfig,
    hyderabad: defaultConfig,
    coimbatore: defaultConfig,
    pondicherry: defaultConfig,
    goa: defaultConfig,
    pune: defaultConfig,
    mysore: defaultConfig,
    tumakuru: defaultConfig,
    noida: defaultConfig,
    gurugram: defaultConfig,
    siliguri: defaultConfig,
    asansol: defaultConfig,
    durgapur: defaultConfig,
    petrapole: defaultConfig,
    trivandrum: defaultConfig,
    thrissur: defaultConfig,
    kozhikode: defaultConfig,
    vellore: defaultConfig,
    hosur: defaultConfig,
    madurai: defaultConfig,
    thanjavur: defaultConfig,
    tirunelveli: defaultConfig,
    salem: defaultConfig,
    trichy: defaultConfig,
    davanagere: defaultConfig,
    shivamogga: defaultConfig,
    hubli: defaultConfig,
    mangalore: defaultConfig,
    gulbarga: defaultConfig,
    udupi: defaultConfig,
    bhubaneswar: defaultConfig,
    cuttack: defaultConfig,
    puri: defaultConfig,
    tamilnaducities: defaultConfig,
    ysCities: defaultConfig,
    alapuzha: defaultConfig,
    idukki: defaultConfig,
    kasarkode: defaultConfig,
    wayanad: defaultConfig,
    kannur: defaultConfig,
    kottayam: defaultConfig,
    palakkad: defaultConfig,
    kolam: defaultConfig,
    default: defaultConfig,
    minneapolis: defaultConfig,
    chandigarh: defaultConfig,
    jaipur: defaultConfig,
    gangtok: defaultConfig,
    darjeeling: defaultConfig,
    vijayawada: defaultConfig,
    vishakapatnam: defaultConfig,
    guntur: defaultConfig,
    tirupati: defaultConfig,
    kurnool: defaultConfig,
    khammam: defaultConfig,
    karimnagar: defaultConfig,
    nizamabad: defaultConfig,
    mahbubnagar: defaultConfig,
    suryapet: defaultConfig,
    nalgonda: defaultConfig,
    siddipet: defaultConfig,
    rourkela: defaultConfig,
    warangal: defaultConfig,
    pudukkottai: defaultConfig,
    bidar: defaultConfig,
    srinagar: defaultConfig,
    pathanamthitta: defaultConfig,
    shillong: defaultConfig,
    cherrapunji: defaultConfig,
    pulwama: defaultConfig,
    jammu: defaultConfig,
    anantnag: defaultConfig,
    berhampur: defaultConfig,
    sambalpur: defaultConfig,
    bardhaman: defaultConfig,
    ballari: defaultConfig,
    amsterdam: defaultConfig,
    digha: defaultConfig,
    rajkot: defaultConfig,
    somnath: defaultConfig,
    dwarka: defaultConfig,
    ahmedabad: defaultConfig,
    surat: defaultConfig,
    vadodara: defaultConfig,
    jamnagar: defaultConfig,
    birbhum: defaultConfig,
};
