import { City, IntercityData } from 'config-types';
// Since this is a static config file, we can't use the dynamic app name approach here.
// We'll have to consider a different solution for this file

export const defaultIntercityRecommendations: Record<City, IntercityData[]> = {
    default: [],
    bangalore: [
        {
            image: 'https://firebasestorage.googleapis.com/v0/b/jp-beckn-dev.appspot.com/o/cubbon_park.png?alt=media&token=3a7edc6c-60f4-4e34-88ee-bd75da3d963d',
            title: 'Trip to Coorg',
            description: '3200',
            fare: 3200,
            buttonImage:
                'https://firebasestorage.googleapis.com/v0/b/jp-beckn-dev.appspot.com/o/Can%20be%20deleted%2Fcar_with_arrow.png?alt=media&token=f86b3b8e-c99f-45f3-a1fd-4503e6c24fe5',
            rideData: {
                lat: 12.4314273,
                lon: 75.7142703,
                title: 'Coorg',
                fullAddress: 'Coorg, Karnataka, India',
            },
        },
    ],
    mumbai: [],
    delhi: [],
    chennai: [],
    kolkata: [],
    paris: [],
    kochi: [],
    hyderabad: [],
    coimbatore: [],
    pondicherry: [],
    goa: [],
    pune: [],
    mysore: [],
    tumakuru: [],
    noida: [],
    gurugram: [],
    siliguri: [],
    asansol: [],
    durgapur: [],
    petrapole: [],
    trivandrum: [],
    thrissur: [],
    kozhikode: [],
    vellore: [],
    hosur: [],
    madurai: [],
    thanjavur: [],
    tirunelveli: [],
    salem: [],
    trichy: [],
    davanagere: [],
    shivamogga: [],
    hubli: [],
    mangalore: [],
    gulbarga: [],
    udupi: [],
    bhubaneswar: [],
    tamilnaducities: [],
    ysCities: [],
    cuttack: [],
    puri: [],
    alapuzha: [],
    idukki: [],
    kasarkode: [],
    wayanad: [],
    kannur: [],
    kottayam: [],
    palakkad: [],
    kolam: [],
    minneapolis: [],
    chandigarh: [],
    jaipur: [],
    gangtok: [],
    darjeeling: [],
    vijayawada: [],
    vishakapatnam: [],
    guntur: [],
    tirupati: [],
    kurnool: [],
    khammam: [],
    karimnagar: [],
    nizamabad: [],
    mahbubnagar: [],
    suryapet: [],
    nalgonda: [],
    siddipet: [],
    rourkela: [],
    warangal: [],
    pudukkottai: [],
    bidar: [],
    srinagar: [],
    pathanamthitta: [],
    shillong: [],
    cherrapunji: [],
    pulwama: [],
    jammu: [],
    anantnag: [],
    berhampur: [],
    sambalpur: [],
    bardhaman: [],
    ballari: [],
    amsterdam: [],
    digha: [],
    rajkot: [],
    somnath: [],
    dwarka: [],
    ahmedabad: [],
    surat: [],
    vadodara: [],
    jamnagar: [],
    birbhum: [],
};
