import { SystemConfigs } from '../types';
import { City } from 'config-types';

const defaultSystemConfigsWithoutCity: SystemConfigs = {
    loggerConfig: {
        chunkSize: 1000000, //1 MB
        timeGranularityInMilliSec: 10000, //50 chunks of eith max 1 MB each or every 10 sec
        chunksLimit: 50, //50 chunks of max 1 MB each
        flushToDiskAfter: 10,
        prodLogSeverityLevel: 'debug',
        logFilePrefix: 'logs-chunkog',
        loggerStateKey: 'logger-state-key',
    },
};

export const defaultSystemConfigs: Record<City, SystemConfigs> = {
    default: defaultSystemConfigsWithoutCity,
    bangalore: defaultSystemConfigsWithoutCity,
    mumbai: defaultSystemConfigsWithoutCity,
    delhi: defaultSystemConfigsWithoutCity,
    chennai: defaultSystemConfigsWithoutCity,
    kolkata: defaultSystemConfigsWithoutCity,
    paris: defaultSystemConfigsWithoutCity,
    kochi: defaultSystemConfigsWithoutCity,
    hyderabad: defaultSystemConfigsWithoutCity,
    coimbatore: defaultSystemConfigsWithoutCity,
    pondicherry: defaultSystemConfigsWithoutCity,
    goa: defaultSystemConfigsWithoutCity,
    pune: defaultSystemConfigsWithoutCity,
    mysore: defaultSystemConfigsWithoutCity,
    tumakuru: defaultSystemConfigsWithoutCity,
    noida: defaultSystemConfigsWithoutCity,
    gurugram: defaultSystemConfigsWithoutCity,
    siliguri: defaultSystemConfigsWithoutCity,
    asansol: defaultSystemConfigsWithoutCity,
    durgapur: defaultSystemConfigsWithoutCity,
    petrapole: defaultSystemConfigsWithoutCity,
    trivandrum: defaultSystemConfigsWithoutCity,
    thrissur: defaultSystemConfigsWithoutCity,
    kozhikode: defaultSystemConfigsWithoutCity,
    vellore: defaultSystemConfigsWithoutCity,
    hosur: defaultSystemConfigsWithoutCity,
    madurai: defaultSystemConfigsWithoutCity,
    thanjavur: defaultSystemConfigsWithoutCity,
    tirunelveli: defaultSystemConfigsWithoutCity,
    salem: defaultSystemConfigsWithoutCity,
    trichy: defaultSystemConfigsWithoutCity,
    davanagere: defaultSystemConfigsWithoutCity,
    shivamogga: defaultSystemConfigsWithoutCity,
    hubli: defaultSystemConfigsWithoutCity,
    mangalore: defaultSystemConfigsWithoutCity,
    gulbarga: defaultSystemConfigsWithoutCity,
    udupi: defaultSystemConfigsWithoutCity,
    bhubaneswar: defaultSystemConfigsWithoutCity,
    cuttack: defaultSystemConfigsWithoutCity,
    puri: defaultSystemConfigsWithoutCity,
    tamilnaducities: defaultSystemConfigsWithoutCity,
    ysCities: defaultSystemConfigsWithoutCity,
    alapuzha: defaultSystemConfigsWithoutCity,
    idukki: defaultSystemConfigsWithoutCity,
    kasarkode: defaultSystemConfigsWithoutCity,
    wayanad: defaultSystemConfigsWithoutCity,
    kannur: defaultSystemConfigsWithoutCity,
    kottayam: defaultSystemConfigsWithoutCity,
    palakkad: defaultSystemConfigsWithoutCity,
    kolam: defaultSystemConfigsWithoutCity,
    minneapolis: defaultSystemConfigsWithoutCity,
    chandigarh: defaultSystemConfigsWithoutCity,
    jaipur: defaultSystemConfigsWithoutCity,
    gangtok: defaultSystemConfigsWithoutCity,
    darjeeling: defaultSystemConfigsWithoutCity,
    vijayawada: defaultSystemConfigsWithoutCity,
    vishakapatnam: defaultSystemConfigsWithoutCity,
    guntur: defaultSystemConfigsWithoutCity,
    tirupati: defaultSystemConfigsWithoutCity,
    kurnool: defaultSystemConfigsWithoutCity,
    khammam: defaultSystemConfigsWithoutCity,
    karimnagar: defaultSystemConfigsWithoutCity,
    nizamabad: defaultSystemConfigsWithoutCity,
    mahbubnagar: defaultSystemConfigsWithoutCity,
    suryapet: defaultSystemConfigsWithoutCity,
    nalgonda: defaultSystemConfigsWithoutCity,
    siddipet: defaultSystemConfigsWithoutCity,
    rourkela: defaultSystemConfigsWithoutCity,
    warangal: defaultSystemConfigsWithoutCity,
    pudukkottai: defaultSystemConfigsWithoutCity,
    bidar: defaultSystemConfigsWithoutCity,
    srinagar: defaultSystemConfigsWithoutCity,
    pathanamthitta: defaultSystemConfigsWithoutCity,
    shillong: defaultSystemConfigsWithoutCity,
    cherrapunji: defaultSystemConfigsWithoutCity,
    pulwama: defaultSystemConfigsWithoutCity,
    jammu: defaultSystemConfigsWithoutCity,
    anantnag: defaultSystemConfigsWithoutCity,
    berhampur: defaultSystemConfigsWithoutCity,
    sambalpur: defaultSystemConfigsWithoutCity,
    bardhaman: defaultSystemConfigsWithoutCity,
    ballari: defaultSystemConfigsWithoutCity,
    amsterdam: defaultSystemConfigsWithoutCity,
    digha: defaultSystemConfigsWithoutCity,
    rajkot: defaultSystemConfigsWithoutCity,
    somnath: defaultSystemConfigsWithoutCity,
    dwarka: defaultSystemConfigsWithoutCity,
    ahmedabad: defaultSystemConfigsWithoutCity,
    surat: defaultSystemConfigsWithoutCity,
    vadodara: defaultSystemConfigsWithoutCity,
    jamnagar: defaultSystemConfigsWithoutCity,
    birbhum: defaultSystemConfigsWithoutCity,
};
