type keyStore =
  | REGISTRATION_TOKEN
  | RECENT_SEARCHES
  | FINDING_RIDE_CREATED_TIME
  | LAST_KNOWN_LOCATION
  | PERSON_ID
  | SESSION_ID

let getKeyStoreValue = (keyStore: keyStore) => {
  switch keyStore {
  | REGISTRATION_TOKEN => "REGISTRATION_TOKEN"
  | RECENT_SEARCHES => "RECENT_SEARCHES"
  | FINDING_RIDE_CREATED_TIME => "FINDING_RIDE_CREATED_TIME"
  | LAST_KNOWN_LOCATION => "LAST_KNOWN_LOCATION"
  | PERSON_ID => "PERSON_ID"
  | SESSION_ID => "SESSION_ID"
  }
}
