type mmkvKey =
  | RECENT_SEARCHES
  | SUGGESTED_LOCATIONS
  | CIRCULAR_PROGRESS_START_TIME
  | PROGRESS_START_TIME
  | RIDE_CHECKS
  | POST_RIDE_CHECKS
  | REGISTRATION_TOKEN

let getMMKVKeyValue = (mmkvKey: mmkvKey) => {
  switch mmkvKey {
  | RECENT_SEARCHES => "RECENT_SEARCHES"
  | SUGGESTED_LOCATIONS => "SUGGESTED_LOCATIONS"
  | CIRCULAR_PROGRESS_START_TIME => "CIRCULAR_PROGRESS_START_TIME"
  | PROGRESS_START_TIME => "PROGRESS_START_TIME"
  | RIDE_CHECKS => "RIDE_CHECKS"
  | POST_RIDE_CHECKS => "POST_RIDE_CHECKS"
  | REGISTRATION_TOKEN => "REGISTRATION_TOKEN"
  }
}
