import { createJourneyId } from '@/typescript/state/client/user';
import { MultimodeTicketUIProps } from './useTicketData';

export const dummyBusTicketData: MultimodeTicketUIProps = {
    renderQR: JSON.stringify({
        mtc: [
            {
                ticketData: [
                    'TICKET_ID',
                    'PASSENGER_NAME',
                    'FROM_STOP',
                    'TO_STOP',
                    'VALID_FROM',
                    'VALID_TO',
                    'RS_50',
                    'TXN_ID',
                    '123456',
                    '#FF0000',
                ],
            },
        ],
    }),
    legTickets: {
        metro: [],
        bus: ['BUS_TICKET_ID_1'],
    },
    transitTypes: [
        {
            title: 'Bus',
            legInfo: {
                estimatedTotalFare: {
                    amount: 23,
                    currency: 'INR',
                },
                totalFare: {
                    amount: 23,
                    currency: 'INR',
                },
                travelMode: 'Bus',
                merchantId: 'merchant-id',
                merchantOperatingCityId: 'merchant-operating-city-id',
                order: 1,
                personId: 'person-id',
                pricingId: 'pricing-id',
                searchId: 'search-id',
                estimatedDistance: {
                    value: 5000,
                    unit: 'Meter',
                },
                actualDistance: {
                    value: 5000,
                    unit: 'Meter',
                },
                bookingAllowed: true,
                estimatedDuration: 300,
                estimatedMaxFare: {
                    amount: 23,
                    currency: 'INR',
                },
                estimatedMinFare: {
                    amount: 23,
                    currency: 'INR',
                },
                estimatedChildFare: {
                    amount: 23,
                    currency: 'INR',
                },
                entrance: undefined,
                exit: undefined,
                hasApplicablePasses: undefined,
                legExtraInfo: {
                    TAG: 'Bus',
                    _0: {
                        frequency: undefined,
                        providerName: 'MTC',
                        routeName: '12B',
                        routeCode: '59',
                        originStop: {
                            code: 'CNT',
                            name: 'Central Bus Stand',
                            address: 'Central Bus Stand',
                            lat: 12.9716,
                            lon: 77.5946,
                            hindiName: 'முதல் நிலை',
                            parentStopCode: undefined,
                            timeTakenToTravelUpcomingStop: undefined,
                            routeCodes: ['12B'],
                            regionalName: 'முதல் நிலை',
                        },
                        destinationStop: {
                            code: 'EGR',
                            name: 'Egmore Bus Stand',
                            address: 'Egmore Bus Stand',
                            lat: 12.9716,
                            lon: 77.5946,
                            hindiName: 'எக்கூர் போக்குவரத்து நிலை',
                            parentStopCode: undefined,
                            timeTakenToTravelUpcomingStop: undefined,
                            routeCodes: ['12B'],
                            regionalName: 'எக்கூர் போக்குவரத்து நிலை',
                        },
                        alternateShortNames: ['12B', '108CX', '108CT', '70V', '70C', '70B', '108CT', '108CX', '12B'],
                        fleetNo: '12B',
                        ticketValidity: ['2025-06-22T20:30:00Z'],
                        tickets: ['12B', '108CX', '108CT', '70V', '70C', '70B', '108CT', '108CX', '12B'],
                        ticketNo: ['12345612334'],
                        bookingId: 'booking-id123',
                        categories: [
                            {
                                categoryId: '89cfaea8-489e-4e9a-9a99-08ba16b327af',
                                categoryName: 'ADULT',
                                categoryOfferedPrice: {
                                    amount: 13.5,
                                    currency: 'INR',
                                },
                                categoryMeta: {
                                    code: 'ADULT',
                                    description: 'Standard ticket category for adult passengers',
                                    title: 'MALE',
                                    tnc: 'Standard terms and conditions apply',
                                },
                                categorySelectedQuantity: 1,
                                categoryPrice: {
                                    amount: 15,
                                    currency: 'INR',
                                },
                            },
                            {
                                categoryId: '36505c11-81ff-4e73-8713-2e68162c3c9e',
                                categoryName: 'FEMALE',
                                categoryOfferedPrice: {
                                    amount: 12.75,
                                    currency: 'INR',
                                },
                                categoryMeta: {
                                    code: 'ADULT',
                                    description: 'Standard ticket category for adult passengers',
                                    title: 'MALE',
                                    tnc: 'Standard terms and conditions apply',
                                },
                                categorySelectedQuantity: 1,
                                categoryPrice: {
                                    amount: 15,
                                    currency: 'INR',
                                },
                            },
                        ],
                        selectedServiceTier: {
                            fare: {
                                amount: 23,
                                currency: 'INR',
                            },
                            quoteId: 'quote-id',
                            serviceTierDescription: 'Ordinary',
                            serviceTierName: 'Ordinary',
                            serviceTierType: 'ORDINARY',
                            trainTypeCode: 'ORDINARY',
                            via: 'ORDINARY',
                        },
                        busConductorId: undefined,
                        busDriverId: undefined,
                        refund: undefined,
                        ticketsCreatedAt: undefined,
                        trackingStatus: undefined,
                        trackingStatusLastUpdatedAt: undefined,
                        discounts: [
                            {
                                code: 'STUDENT_DISCOUNT',
                                title: 'Student Discount',
                                description: 'Special discount for students',
                                eligibility: true,
                                price: {
                                    amount: 5,
                                    currency: 'INR',
                                },
                                tnc: 'Terms and conditions apply',
                            },
                            {
                                code: 'SENIOR_DISCOUNT',
                                title: 'Senior Citizen Discount',
                                description: 'Discount for senior citizens',
                                eligibility: false,
                                price: {
                                    amount: 3,
                                    currency: 'INR',
                                },
                                tnc: 'Valid for citizens above 60 years',
                            },
                        ],
                    },
                },
                startTime: '2025-06-22T18:00:00Z',
                bookingStatus: {
                    TAG: 'Initial',
                    _0: 'BOOKING_PENDING',
                },
                journeyLegId: '',
                validTill: undefined,
            },
            AltText: '',
        },
    ],
    comboTicketText: 'Bus Combo Ticket',
    journeyId: createJourneyId('DUMMY_JOURNEY_ID'),
    bottomInset: 0,
    onDismiss: () => {},
    onClose: () => {},
    onStartJourney: () => {},
    onQuestionPress: () => {},
    onShare: () => {},
    fromLiveJourney: false,
    showStartJourneyButton: true,
    isPopUp: false,
    appName: 'anna',
    onPress: () => {},
    paymentDetailsData: {
        orderId: 'orderId',
        totalAmount: '10',
        dateAndTime: 'dd/mm/yy',
    },
    onPressBookAuto: () => {},
};
