source "https://rubygems.org"

gem "fastlane", ">= 2.222.0"
gem "abbrev"
gem "mutex_m"
gem "ostruct"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
